### ISSUE TITLE
JAVA 8

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1001]
Related to https://groups.google.com/forum/#!topic/h2-database/PqkMtCU1Yvg

**Comment by nicolas-f** [comment]
It is already set to minimum java 8
        <maven.compiler.target>8</maven.compiler.target>
        <maven.compiler.source>8</maven.compiler.source>

**Comment by katzyn** [comment]
And JTS that you use requires Java 8 as well.
