### ISSUE TITLE
SpatialTreeIndex vs MVSpatialIndex

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1003]
Do we need to change the SpatialTreeIndex that uses pagestore to the MVSpatialIndex ?

https://github.com/h2database/h2database/blob/3df0426d9f519ac35d2882413b273108cd9432ca/h2/src/main/org/h2/mvstore/db/MVSpatialIndex.java

**Comment by nicolas-f** [comment]
We already use MVSpatialIndex on MVStore mode and SpatialTreeIndex on pagestore mode

**Comment by ebocher** [comment]
Thanks I close it

**Comment by katzyn** [comment]
`SpatialTreeIndex` is a dirty hack, I don't think that old PageStore engine is suitable for anyone who need a `SPATIAL` index. Such database uses both PageStore and MVStore backends together and may be affected by possible problems from both of them.

**Comment by ebocher** [comment]
I'm agree with @katzyn . We must use MVStore. This will involve some changes for H2Table class in H2GIS.

**Comment by ebocher** [comment]
https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/H2Table.java#L120

**Comment by nicolas-f** [comment]
Oh, yeah, I didn't see that, sorry.

H2Table need to be updated yes. This class was a hack to add spatial index on linked shape files.

**Comment by ebocher** [comment]
Not so  straightforward because  we have to use a MVStore and MVTable

**Comment by ebocher** [comment]
Fix.
Not we use only mvstore system
