### ISSUE TITLE
H2 1.4.201 will have some changes with JTS geometries

### ISSUE THREAD

**Issue by katzyn** [orbisgis/h2gis#1004]
The support of JTS 1.15 was dropped in H2 and some code was changed it result. JTS 1.15 doesn't really support the M dimension, with 1.16 situation is much better, but JTS still has own bugs; its `WKTReader`, for example, creates three dimensions for XY geometries.

Recent versions of H2 don't use I/O classes of JTS and produce the geometries by own code.

H2 1.4.200 creates 3 dimensions in absence of M dimension and 4 dimensions (including 1 measure in case of JTS 1.16) in presence of it. XY and M geometries have unused Z dimension that is filled with NaNs. That logic was required for JTS 1.15.

H2 1.4.201 will always use the correct coordinate sequences. The XY geometry will have 2 dimensions and 0 measures, Z geometries will have 3 dimensions and 0 measures, M geometries will have 3 dimensions including 1 measure, ZM geometries will have 4 dimensions including 1 measure. Unused dimensions will not be created any more.

The related change was pushed to the `master` branch of H2 on GitHub, you can build H2 from its current sources and test it, if you wish. I have no idea whether H2GIS is affected by this change or not, but you had some problems with dimensions in the past, so I want to warn you that code that works with additional dimensions should be tested again.

**Comment by ebocher** [comment]
done
