### ISSUE TITLE
conflict when using orbisdata and sql.Connection ?

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/h2gis#1015]
I am currently applying the code developed by @gpetit for recovering the right location of the BDTopo data from the server.
First, it worked well.
I have decided to add a function to save all tables included in the H2GIS database. To achieve this I used the getTableNames and save functions and thus need the orbisdata dependency.

However, since I have added this dependency (below) it does not work anymore
```groovy
@GrabResolver(name='orbisgis',` root='http://nexus-ng.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisdata.datamanager', module='jdbc', version='1.0.1-SNAPSHOT')
```
I got the resulting error message:
> AVERTISSEMENT: Failed to execute: CREATE TABLE iris_ge(PK integer, THE_GEOM geometry, INSEE_COM varchar) AS SELECT * FROM IRIS_TEMP; because: Erreur générale: "java.lang.IllegalAccessError: class org.h2gis.postgis_jts.JtsBinaryParser tried to access protected method 'void org.locationtech.jts.geom.impl.PackedCoordinateSequence.<init>(int, int)' (org.h2gis.postgis_jts.JtsBinaryParser and org.locationtech.jts.geom.impl.PackedCoordinateSequence are in unnamed module of loader org.codehaus.groovy.tools.RootLoader @30f39991)"
General error: "java.lang.IllegalAccessError: class org.h2gis.postgis_jts.JtsBinaryParser tried to access protected method 'void org.locationtech.jts.geom.impl.PackedCoordinateSequence.<init>(int, int)' (org.h2gis.postgis_jts.JtsBinaryParser and org.locationtech.jts.geom.impl.PackedCoordinateSequence are in unnamed module of loader org.codehaus.groovy.tools.RootLoader @30f39991)"; SQL statement:
CREATE TABLE iris_ge(PK integer, THE_GEOM geometry, INSEE_COM varchar) AS SELECT * FROM IRIS_TEMP; [50000-197]
Caught: org.h2.jdbc.JdbcSQLException: Erreur générale: "java.lang.IllegalAccessError: class org.h2gis.postgis_jts.JtsBinaryParser tried to access protected method 'void org.locationtech.jts.geom.impl.PackedCoordinateSequence.<init>(int, int)' (org.h2gis.postgis_jts.JtsBinaryParser and org.locationtech.jts.geom.impl.PackedCoordinateSequence are in unnamed module of loader org.codehaus.groovy.tools.RootLoader @30f39991)"
General error: "java.lang.IllegalAccessError: class org.h2gis.postgis_jts.JtsBinaryParser tried to access protected method 'void org.locationtech.jts.geom.impl.PackedCoordinateSequence.<init>(int, int)' (org.h2gis.postgis_jts.JtsBinaryParser and org.locationtech.jts.geom.impl.PackedCoordinateSequence are in unnamed module of loader org.codehaus.groovy.tools.RootLoader @30f39991)"; SQL statement:
CREATE TABLE iris_ge(PK integer, THE_GEOM geometry, INSEE_COM varchar) AS SELECT * FROM IRIS_TEMP; [50000-197]
org.h2.jdbc.JdbcSQLException: Erreur générale: "java.lang.IllegalAccessError: class org.h2gis.postgis_jts.JtsBinaryParser tried to access protected method 'void org.locationtech.jts.geom.impl.PackedCoordinateSequence.<init>(int, int)' (org.h2gis.postgis_jts.JtsBinaryParser and org.locationtech.jts.geom.impl.PackedCoordinateSequence are in unnamed module of loader org.codehaus.groovy.tools.RootLoader @30f39991)"
General error: "java.lang.IllegalAccessError: class org.h2gis.postgis_jts.JtsBinaryParser tried to access protected method 'void org.locationtech.jts.geom.impl.PackedCoordinateSequence.<init>(int, int)' (org.h2gis.postgis_jts.JtsBinaryParser and org.locationtech.jts.geom.impl.PackedCoordinateSequence are in unnamed module of loader org.codehaus.groovy.tools.RootLoader @30f39991)"; SQL statement:
CREATE TABLE iris_ge(PK integer, THE_GEOM geometry, INSEE_COM varchar) AS SELECT * FROM IRIS_TEMP; [50000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:303)
	at org.h2.command.Command.executeUpdate(Command.java:274)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at Script-4.importData(Script-4.groovy:180)
	at Script-4$importData$1.callCurrent(Unknown Source)
	at Script-4.processing(Script-4.groovy:109)
	at Script-4$processing.callCurrent(Unknown Source)
	at Script-4.run(Script-4.groovy:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)>

The complete code I have run is available at: [https://github.com/gpetit/paendora/blob/master/paendora_chain.groovy](url)
And the import causing the problem is the following:
`import org.orbisgis.orbisdata.datamanager.jdbc.h2gis.H2GIS;`

**Comment by SPalominos** [comment]
As the issue is related to h2gis, I transfer it

**Comment by SPalominos** [comment]
@j3r3m1 According to @gpetit , the issue seems to be fixes. He will update the script you have used and before rerunning it, delete you `.groovy` folder (do not forget to close the groovyConsole before if you are using it)

**Comment by gpetit** [comment]
@j3r3m1 Hop, the `paendora_chain.groovy` file has been updated with the new dependencies and the new syntax for indexes

**Comment by j3r3m1** [comment]
OK no trouble anymore, I can load both classes (orbisdata and sql)
