### ISSUE TITLE
Operation with mixed SRID

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1016]
In H2GIS
```sql
SELECT ST_Intersects(
		'SRID=4326;LINESTRING(-43.23456 72.4567,-43.23456 72.4568)'::geometry,
		'SRID=30251;POINT(-43.23456 72.4567772)'::geometry
		);
```
return true

In PostGIS -> ERREUR: Operation on mixed SRID geometries

So I propose to update all functions to test if the SRID are mixed

**Comment by ebocher** [comment]
@gpetit @j3r3m1

**Comment by gpetit** [comment]
+1 If mixed SRID than error

**Comment by j3r3m1** [comment]
yes, what happens if there is no SRID for two geometries ? If only one of them do not have ?

**Comment by ebocher** [comment]
if no srid -> no pb
i fonly one of them do not have -> mixed -> so error

**Comment by j3r3m1** [comment]
Isn't it a problem to have no SRID on geometries (then to make it works for two geometries that have no SRID) ?

**Comment by ebocher** [comment]
JTS do geometry ops without taking into account the srid

**Comment by ebocher** [comment]
Fixed.
Now doc for @gpetit
