### ISSUE TITLE
Types.JAVA_OBJECT should not be used for GEOMETRY

### ISSUE THREAD

**Issue by katzyn** [orbisgis/h2gis#1027]
In the next version of H2 (201) combination of `Types.JAVA_OBJECT` and `"GEOMETRY"` in a some column of `SimpleResultSet` will not be recognized as a `GEOMETRY` data type any more when a table value function returns such result set. `ST_ShortestPath`, `ST_ShortestPathTree` and possibly other places should be adjusted to use `Types.OTHER` with `"GEOMETRY"` name instead.

**Comment by ebocher** [comment]
Thanks I will check
