### ISSUE TITLE
Instructions on Wiki section 4.4 can be simplified

### ISSUE THREAD

**Issue by reinvantveer** [orbisgis/h2gis#1029]
https://github.com/orbisgis/h2gis/wiki/4.4-Use-H2GIS-with-Python/fd9cb870363f72aea3032b5ce4f54ca124386831#run-h2gis-as-a-posgresql-sever-mode
can simply be rewritten as:

`java -cp "bin/*" org.h2.tools.Server -pg` for *any* platform

The sweet parts of this is that this instruction is both short, h2gis-version agnostic and platform-agnostic.

**Comment by reinvantveer** [comment]
Ok I have to admit that I have no Mac machine available to test this for all platforms 🤔

**Comment by SPalominos** [comment]
@reinvantveer Thank you, it work on OSX (at least on 10.14).
