### ISSUE TITLE
Driver read and write compressed files

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/h2gis#1035]
Offer the possibility to compress exported file according to the extension provided and also to read compressed files.
As example with a file name 'MyFile.tar.gz' as output will compress the data into a  `tar.gz` file

**Comment by ebocher** [comment]
Fixed 
Doc must be update @gpetit

**Comment by ebocher** [comment]
Works for all drivers expected shp and dbf

**Comment by ebocher** [comment]
Done here #1120
