### ISSUE TITLE
GeoJSON reading error starting with null value

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/h2gis#1042]
When I try to read a file starting with a null value, I got the following error:
> SQL Error [22018] [22018]: Erreur lors de la conversion de données "'null' (BUILD: ""ID_RSU"" BIGINT)"
Data conversion error converting "'null' (BUILD: ""ID_RSU"" BIGINT)"; SQL statement:
INSERT INTO "BUILD" VALUES(?,?,?,?,?,?,?,?,?,?,?,?) [22018-200];
while it works well if I read the same file but inverting the position of the rows (start with not null).

Attached two files with the two same rows but in the inverted positions.
[Files.zip](https://github.com/orbisgis/h2gis/files/4254152/Files.zip)

**Comment by j3r3m1** [comment]
Note that a temporary solution to avoid this problem is to save the file using ORDER BY colWithNull DESC.
However, if several columns contain null values, then I am not sure it would still work...

**Comment by SPalominos** [comment]
I'm taking a look on that

**Comment by SPalominos** [comment]
Should be fixed with the PR #1044

**Comment by j3r3m1** [comment]
OK solved
