### ISSUE TITLE
1.5.X on repo.orbisgis.org

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis#1055]
Hi,

We (noisemodelling) are using 1.5.X branch, but this branch is not available on orbisgis repository.

Could you add a job on https://jenkins.orbisgis.org in order to build branch H2GIS 1.5.X snapshot ?

Thanks

**Comment by SPalominos** [comment]
You can now retrieve H2GIS 1.5.x on [nexus.orbisgis.org](http://nexus.orbisgis.org/), see [here](http://nexus.orbisgis.org/#browse/browse:orbisgis-snapshot:org%2Forbisgis%2Fh2gis%2F1.5.1-SNAPSHOT)

**Comment by nicolas-f** [comment]
Great! Thanks a lot!
