### ISSUE TITLE
OSM update option

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1057]
Add an option to the OSM driver to update the OSM tables if the tables already exists.

We have

OSMRead(VARCHAR path, VARCHAR tableName, BOOLEAN deleteTables);

if deleteTables = true then delete
if deleteTables = false and tables exists then throw exception
else do the job

I propose 

if deleteTables = true then delete
if deleteTables = false and tables exists then update the tables
else do the job

**Comment by j3r3m1** [comment]
So you will check all id ? What if there are new columns in the incoming table ? You join ?

**Comment by ebocher** [comment]
I will check if the database contains node, relation, way id.

**Comment by nicolas-f** [comment]
Why is this option necessary? Do you find it easy to do?

**Comment by ebocher** [comment]
This option is necessary to refresh the OSM tables when a diff file is published.

**Comment by nicolas-f** [comment]
This is diff file formats ? 

https://wiki.openstreetmap.org/wiki/Planetdiff

**Comment by ebocher** [comment]
Yep so the original idea is stupid... thanks @nicolas-f to refresh me  
We need another function.
