### ISSUE TITLE
Geojson BigInteger fix

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1106]
To be added in master
https://github.com/orbisgis/h2gis/pull/1103#issuecomment-655939593

**Comment by ebocher** [comment]
I close this issue because BigInt already works in 2.0

**Comment by nicolas-f** [comment]
Its works because of update to postgis-jdbc 2.5 (h2gis 1.5 use 2.3)

But we use 8 bytes in db for storing 4 bytes integer from json.

**Comment by ebocher** [comment]
PR welcome ;-)
