### ISSUE TITLE
Typo in the SHPRead function

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#1111]
Why two times the same signature lines 51 and 52 ?

https://github.com/orbisgis/h2gis/blob/189a181854583b1bc88f76145cc23eec96e8b69b/h2gis-functions/src/main/java/org/h2gis/functions/io/shp/SHPRead.java#L52

**Comment by ebocher** [comment]
Done

**Comment by ebocher** [comment]
Done here #1120

**Comment by gpetit** [comment]
Thx
