### ISSUE TITLE
ASCRead bugs and improvements

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#1113]
While doing the documentation, I have two remarks and one bug

### Remarks

Replace `SQL function to import ESRI ASCII Raster file as polygons table.` by `... as points or polygons table.`
https://github.com/orbisgis/h2gis/blob/59ba2183ef09cd43f368d1b3c7fdbec26a71e29e/h2gis-functions/src/main/java/org/h2gis/functions/io/asc/AscRead.java#L34

Why `AS_POINTS` since if `true` then the pixels are converted to polygons? We should name this parameter `AS_POLYGONS`
https://github.com/orbisgis/h2gis/blob/59ba2183ef09cd43f368d1b3c7fdbec26a71e29e/h2gis-functions/src/main/java/org/h2gis/functions/io/asc/AscRead.java#L52

### Bug

It seems to me there is a bug with the (`path, tablename`) signature.

I executed this
```sql
CALL ASCRead('/home/gpetit/MNT_L93.asc', 'TITI');
```
The table `TITI` is well created with all the points.
Then I execute this

```sql
CALL ASCRead('/home/gpetit/MNT_L93.asc', 'TOTO');
```
And I have this error message
```
Unexpected word -99999.00; SQL statement:
call ascread('/home/gpetit/MNT_L93.asc', 'TITI') [0-200] null/0 (Aide)
```
It seems that if the ascii file as already been called, we are not able to load it once again in another table

Just to be sure I executed this
```sql
DROP TABLE TITI;
CALL ASCRead('/home/gpetit/MNT_L93.asc', 'TOTO');
```
And the table `TOTO` is well created.

@nicolas-f @ebocher @SPalominos

**Comment by gpetit** [comment]
Ok, @ebocher found that the problem come from the `CONSTRAINT ASC_PK PRIMARY KEY (PK))`. Every ASC table have this same `ASC_PK` constraint and it's not possible. 
A PR should be in the pipe

**Comment by nicolas-f** [comment]
The ASC reader does not support float cell values

**Comment by gpetit** [comment]
Not sure to understand.
The problem here is not the constraint. The problem is that every table made from an ASC import have the same constraint name, which is not allowed. So if you CALL file1.asc and then file2.asc, H2GIS will detect that there is already a constraint called ASC_PK ... and crash

**Comment by nicolas-f** [comment]
Yes we should remove the constraint name (I don't think its mandatory)

The error message is not complete. You should have the SQL exception with it.

**Comment by ebocher** [comment]
CONSTRAINT ASC_PK PRIMARY KEY (PK)) is not necessary.
Delete this constraint will be enough to fix the issue.

**Comment by ebocher** [comment]
Fixed

**Comment by gpetit** [comment]
@nicolas-f any opinion about my two remarks at the beginning ?
