### ISSUE TITLE
ASCRead - pblm with the TYPE parameter

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#1118]
When using the `type` parameter in the `ASCRead` function I have a problem. If I execute

```sql
CALL ASCREAD('/home/gpetit/dem.asc', 1);
-- or
CALL ASCREAD('/home/gpetit/dem.asc', 'myDEMTable', 1);
```
In both cases, I have this error message
```
Please use 1 for integer or 2 for double conversion; SQL statement:
```
After investigation, it seems that the problem come from this line https://github.com/orbisgis/h2gis/blob/08f2e7c80cbfa7f9d3c1ca108f15c06ef07a6ad0/h2gis-functions/src/main/java/org/h2gis/functions/io/asc/AscRead.java#L92

since `ValueInteger` is a Java object that can not been compared to an integer (cf `if (zType != 1 || zType != 2)` line 94)

@ebocher @nicolas-f

**Comment by nicolas-f** [comment]
The issue here is the boolean condition
For an error to be thrown condition A **or** condition B must be true
A is true if zType is not equal to 1
B is true if zType is not equal to 2

So zType must be equal to 1 and equal to 2 to not throw an error. This will be difficult.

The real test is:

```java
if (!(zType == 1 || zType == 2)) {
```
or

```java
if (zType < 1 || zType > 2) {
```

**Comment by ebocher** [comment]
Done thanks

**Comment by ebocher** [comment]
Done here #1120

**Comment by gpetit** [comment]
Nice. Thx
