### ISSUE TITLE
ASCRead - type conversion depending of the signature

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#1119]
Still testing the ASCRead function. It seems that the `type` conversion (into INTERGER or DOUBLE) is not working in the same way depending of the signature used.

I have the following `dem.asc` file, with INTEGER Z values:
```
ncols        4
nrows        4
xllcorner    10
yllcorner    10
cellsize     5.0
NODATA_value  -9999
 28 27 26 25
 27 25 24 23
 26 23 20 19
 25 20 18 17
```
Now I'm calling this file
```mysql
CALL ASCREAD('/home/user/dem.asc');
-- or
CALL ASCREAD('/home/user/dem.asc', 'myDEMTable');
```
Returns **double** Z value
|   PK  | THE_GEOM |  Z  |
|:-----:|:--------:|:---:|
| 1 |    POINT Z (12.5 27.5 28)   | **28.0** |
| ... |    ...   | ... |

Now, I use this signature `ASCRead(VARCHAR path, VARCHAR myTable, GEOMETRY geomFilter, INTEGER downScaleInt, BOOLEAN asPolygons);` (so in theory there is no Z conversion since we don't use the `type` parameter) we have

```mysql
CALL ASCREAD('/home/user/dem.asc', 'myDEMTable', null, 1, false);
```
Returns **integer** Z value
|   PK  | THE_GEOM |  Z  |
|:-----:|:--------:|:---:|
| 1 |    POINT Z (12.5 27.5 28)   | **28** |
| ... |    ...   | ... | 

So to summarize
- entry asc file : Z values are **INTEGER**
- resulting Z values when using `ASCRead(VARCHAR path);` or `ASCRead(VARCHAR path, VARCHAR myTable);` are **DOUBLE**
- resulting Z values when using `ASCRead(VARCHAR path, VARCHAR myTable, GEOMETRY geomFilter, INTEGER downScaleInt, BOOLEAN asPolygons);` are **INTEGER**

I made a test with a ASC file in which there is double Z values
```
ncols        4
nrows        4
xllcorner    10
yllcorner    10
cellsize     5.0
NODATA_value  -9999
 28.2 27.5 26.4 25.6
 27.1 25.7 24.6 23.3
 26.4 23.2 20.1 19.0
 25.7 20.9 18.4 17.2
```

And I have the same results: 
- entry asc file : Z values are **DOUBLE**
- resulting Z values when using `ASCRead(VARCHAR path);` or `ASCRead(VARCHAR path, VARCHAR myTable);` are **DOUBLE**
- resulting Z values when using `ASCRead(VARCHAR path, VARCHAR myTable, GEOMETRY geomFilter, INTEGER downScaleInt, BOOLEAN asPolygons);` are **INTEGER**

So we can conclude that:
- `ASCRead(VARCHAR path);` or `ASCRead(VARCHAR path, VARCHAR myTable);` signatures convert Z values into **DOUBLE**
- `ASCRead(VARCHAR path, VARCHAR myTable, GEOMETRY geomFilter, INTEGER downScaleInt, BOOLEAN asPolygons);` signatures convert Z values into **INTEGER** 

Right ? Is it a normal (or wanted) behaviour ?

PS: I did not test the `ASCRead(VARCHAR path, INTEGER type);` and `ASCRead(VARCHAR path, VARCHAR myTable, INTEGER type);` signatures since they don't work right now (cf #1118 )

@nicolas-f @ebocher

**Comment by gpetit** [comment]
In fact, I think we should follow this principle : 
- When using the following signatures ( `ASCRead(VARCHAR path);` , `ASCRead(VARCHAR path, VARCHAR myTable);`or `ASCRead(VARCHAR path, VARCHAR myTable, GEOMETRY geomFilter, INTEGER downScaleInt, BOOLEAN asPolygons);`) we should keep the Z type since the `type` parameter is not used -> no conversion
- When using the following signatures (`ASCRead(VARCHAR path, INTEGER type);` or `ASCRead(VARCHAR path, VARCHAR myTable, INTEGER type);`), the Z value is converted

**Comment by gpetit** [comment]
I forgot the fact that it is not possible to determine in advance whether the Z value is `DOUBLE` or `INTEGER`. 
Therefore, all `Z` values are `DOUBLE` by default.

So, the principle should be like this:

- When using the following signatures: 
    - `ASCRead(VARCHAR path);`
    - `ASCRead(VARCHAR path, VARCHAR myTable);`
    - `ASCRead(VARCHAR path, VARCHAR myTable, GEOMETRY geomFilter, INTEGER downScaleInt, BOOLEAN asPolygons);`   
    - --> the `Z` type remains `DOUBLE` -> no conversion
- When using the following signatures: 
    - `ASCRead(VARCHAR path, INTEGER type);`
    - `ASCRead(VARCHAR path, VARCHAR myTable, INTEGER type);` 
    - --> the `Z` type may be converted

**Comment by ebocher** [comment]
Done here #1120

**Comment by gpetit** [comment]
Thx. Solved
Since all the Z values are in double, except when the `type` is equal to `1`, one could wonder if this parameter should not be a boolean instead.
E.g: `type` is renamed `toInteger`. If  `toInteger`= yes --> the Z value is casted to INT (default = false)

Any comments @ebocher @nicolas-f ?

**Comment by ebocher** [comment]
Good idea

**Comment by ebocher** [comment]
Because we can imagine
