### ISSUE TITLE
Implement ST_PolygonSmoothing or enhance ST_Densify

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis#1121]
As already implemented in NoiseModelling.

input:
- MultiPolygon in XYM or XYZM coordinates
- smooth coefficient

processing:
Collect common segment (same XY nodes) between polygons with M value different. Only shared segments will be smoothed.
Apply bezier curve on sequence of touching segments. If new curve is touching other linestring reduce the smooth coefficient for that linestring (maybe find a way to compute maximum smooth coefficient beforehand)
Reconstruct the polygons with the smoothed linestring
Return the new multipolygon

ref: https://github.com/Ifsttar/NoiseModelling/blob/v3.2.1/noisemodelling-emission/src/main/java/org/noise_planet/noisemodelling/emission/jdbc/BezierContouring.java
http://agg.sourceforge.net/antigrain.com/research/bezier_interpolation/index.html#PAGE_BEZIER_INTERPOLATION

**Comment by ebocher** [comment]
Any plan ?

**Comment by nicolas-f** [comment]
Not for next release of H2GIS. Smoothing of polygons may create intersections, there is currently no implementation to avoid this issue.

**Comment by ebocher** [comment]
@nicolas-f 
Do you plan to work on this issue one day , otherwise I'll close it

**Comment by nicolas-f** [comment]
Hello. Yes you can close it
