### ISSUE TITLE
ASCRead - issue when reading .asc.gz file

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#1122]
When opening an `.asc` file which is in a `.gz` file there is a problem with the first signature (`ASCRead(VARCHAR path);`)
For example
```sql
CALL ASCREAD('/home/user/dem.asc.gz');
```
Returns
```
The file name contains unsupported characters; SQL statement:
```
This error is due to the fact that the ASC driver try to create a table named `dem.asc`, which is not allowed.

If we use the second signature (`ASCRead(VARCHAR path, VARCHAR myTable);`) (and following), it works well since the `myTable` parameter wins against `path`.

@ebocher @nicolas-f

**Comment by ebocher** [comment]
Done here https://github.com/orbisgis/h2gis/pull/1120

**Comment by gpetit** [comment]
Nice. Thx
Now, the `dem.asc.gz` file gives `DEM_ASC` table
