### ISSUE TITLE
UpdateGeometrySRID - returns FALSE in any case

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#1124]
Reading the code source, we can see

```
     * @param connection active connection to the database
     * @param table_name name of the tabe
     * @param column_name name of the geomtry column
     * @param srid value of the new srid
     * @return true if the SRID is changed
```
So this function is supposed to return `TRUE` is the SRID has been changed.

So I execute this script
```mysql
CREATE TABLE geo_point (the_geom GEOMETRY(POINT));
INSERT INTO geo_point VALUES('SRID=0;POINT(0 0)');
SELECT ST_SRID(the_geom) as SRID FROM geo_point;
```
it returns SRID = 0 --> well

Now, lets update the SRID
```mysql
SELECT UpdateGeometrySRID('GEO_POINT','THE_GEOM',4326);
```
It returns `FALSE` but if I check with

```mysql
SELECT ST_SRID(the_geom) as SRID FROM geo_point;
```
I have SRID = 4326

So the SRID has been updated as expected ... even if the `UpdateGeometrySRID` returns `FALSE`

I also tried to update the SRID with the same value (4326 --> 4326). So in theory there is no modification, but once again, `UpdateGeometrySRID` returns `FALSE`.

So am I missing something ? Is there a case where `UpdateGeometrySRID` returns `TRUE` ?

@ebocher @SPalominos

**Comment by ebocher** [comment]
Done

**Comment by gpetit** [comment]
I will check tomorrow since the [build 1136](https://jenkins.orbisgis.org/job/H2GIS/1136/) seems to not integrate your PR.

In the meantime, why when the SRID is well updated, it returns `FALSE` (in a column named `FALSE`) ? 
![image](https://user-images.githubusercontent.com/1871248/94158477-b723c600-fe82-11ea-85aa-2d3b163b10b6.png)


It should returns `TRUE` (in a column named `UPDATED` (or something like that))!?

**Comment by gpetit** [comment]
Just made the test with the [build 1139](https://jenkins.orbisgis.org/job/H2GIS/1139/)

In any cases, the `UpdateGeometrySRID` function retunrs `FALSE` even if the SRID has been well updated

**Comment by katzyn** [comment]
This function shouldn't be deterministic. Deterministic functions may be optimized out by H2.

**Comment by ebocher** [comment]
Fixed thanks @katzyn

**Comment by gpetit** [comment]
No modifications for me. Still returning `FALSE` whatever I'm doing
