### ISSUE TITLE
ASCRead - deleteTable error message

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#1126]
We can use the `deleteTable` parameter when reading an ASC file.

When the table `myDEMTable` already exists and we use `deleteTable`=`false` we have an error message.
In theory, this message should warn that the table already exists but for this function (ASCRead) all the messages are this one

```
Unexpected word -9999; SQL statement:
CALL ASCREAD('/home/gpetit/dem.asc', 'myDEMTable', null, 2, true, false) [0-200] null/0 (Aide)
```

Is it possible to align the message with the other driver (see example below)
![image](https://user-images.githubusercontent.com/1871248/94244847-c3a72d80-ff19-11ea-8839-214628a23f73.png)

@ebocher @SPalominos

**Comment by ebocher** [comment]
Fixed

**Comment by gpetit** [comment]
Sorry, still the same weird error message
```
Unexpected word -9999; SQL statement:
CALL ASCREAD('/home/gpetit/dem.asc', false) [0-200] null/0 (Aide)
```

**Comment by nicolas-f** [comment]
The error message is not complete. Where do you see this error message ?

**Comment by gpetit** [comment]
In the H2 Console (in Firefox) when executing my H2GIS / SQL scripts

**Comment by nicolas-f** [comment]
Maybe upload the databasename.trace.db ?

**Comment by gpetit** [comment]
I just loaded this dem.asc file (inside the [dem.zip](https://github.com/orbisgis/h2gis/files/5312003/dem.zip))

```mysql
CALL ASCREAD('/home/gpetit/dem.asc', 'myDEMTable');
```
Table `myDEMTable` is created
Then 
```mysql
CALL ASCREAD('/home/gpetit/dem.asc', 'myDEMTable',true);
```
--> Ok
Then
```mysql
CALL ASCREAD('/home/gpetit/dem.asc', 'myDEMTable',false);
```
--> 
```
Unexpected word -9999; SQL statement:
CALL ASCREAD('/home/gpetit/dem.asc', false) [0-200] null/0 (Aide)
```
