### ISSUE TITLE
SHPRead with null value

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#1132]
I have a shapefile in which there is many null values (on the attribute side, not on the geometry).
I discovered that we have an issue with `numeric` fields

I have a shapefile (`road_noise.shp`), structured as follow:

- `THE_GEOM` : Linestring
- `ID` : String
- `MYTEXT` : String
- `MYREAL` : Real

Filled with these values

| THE_GEOM | ID | MYTEXT | MYREAL |
|:--:|:--:|:--:|:--:|
| LINESTRING((...)) | 1  |   |  |
| LINESTRING((...)) | 2  |   |  |

Now I want to read this shapefile
```mysql
CALL shpread('/home/user/road_noise.shp','noise');
```

I get this error message
```
INSERT INTO "NOISE" VALUES (DEFAULT, ?, ?, ?, ? )
null; SQL statement:
call shpread('/home/gpetit/test/road_noise.shp','noise') [0-200] null/0 (Aide)
```

Now I remove the `MYREAL` column and tried to load the shapefile again. I obtain the `NOISE` table

| PK | THE_GEOM | ID | MYTEXT |
|:--:|:--:|:--:|:--:|
| 1 | LINESTRING((...))  |  1  |  |
| 2 | LINESTRING((...))  |  2  |  |

**Comment by ebocher** [comment]
Fixed
