### ISSUE TITLE
[Discussion] Get build in function by name

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1136]
The H2GIS functions area registered with new Function[] {....
There is no simple way to get a function from its name.
So I propose to add a method public static Function getFunction(String name)  and populate in H2GISFunctions a hasmap instead of  Function[]
something like : 
private static HashMap<String, Class<? extends Function>> nameFunction = new HashMap<String, Class<? extends Function>>();
I want to use the same approach we had in GDMS. see https://github.com/orbisgis/orbisgis/blob/legacy/orbisgis_se-3.1/gdms/src/main/java/org/gdms/sql/function/FunctionManager.java#L177

Note :  H2 offers a BuiltinFunctions

@nicolas-f  @SPalominos  is it ok for you ?

**Comment by nicolas-f** [comment]
Hello, this map would not reflect the functions actually available in the database.

Why not use jdbc and system table to get the functions by name ?
If you are in OSGi environment you can also get the list of services that implement org.h2gis.api.Function

**Comment by ebocher** [comment]
This map reflect the internal build in functions provided by H2GIS.

> Why not use jdbc and system table to get the functions by name ?
Because I want to know only the build in functions and not the functions registered by the db

**Comment by ebocher** [comment]
I closed this issue because it can be done with the following code.

```
            JdbcConnection jdbcConnection = (JdbcConnection) con;
            Session session = (Session) jdbcConnection.getSession();
            Database database = session.getDatabase();
            FunctionAlias function = database.getSchema("PUBLIC").findFunction("ST_BUFFER");
```
