### ISSUE TITLE
ST_AsText() fails to return z

### ISSUE THREAD

**Issue by claeis** [orbisgis/h2gis#1157]
```
sql> SELECT ST_AsText(ST_GeomFromText('POINT(2460001 1045001 300)'));
'POINT (2460001 1045001)'
```
Change https://github.com/orbisgis/h2gis/blob/1d5cf3fc31aa5a2dcb154777d82c81adcba812c6/h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/ST_AsWKT.java#L53 to

    WKTWriter wktWriter = new WKTWriter(3);

**Comment by ebocher** [comment]
Thanks a lot
Fixed https://github.com/orbisgis/h2gis/pull/1189
