### ISSUE TITLE
Trouble with duplicate columns in ST_EXPLODE

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/h2gis#1184]
I have the following duplicated column error 
`SQL Error [42121] [42S21]: Duplication du nom de colonnes "ID"
Duplicate column name "ID"; SQL statement:`

when I run the following SQL code:
```sql
CREATE TABLE FIN 
	AS SELECT 	ID_A,
                                ID_B,
                                THE_GEOM
FROM ST_EXPLODE('(SELECT 	a.ID AS ID_A,
				b.ID AS ID_B, 
				ST_INTERSECTION(a.the_geom, b.the_geom) AS the_geom
		FROM TAB1 AS a, TAB2 AS b
		WHERE ST_INTERSECTS(a.the_geom, b.the_geom))')
```
Is it a bug or the expected behavior ?

Note that to avoid the bug, I did a a.ID_A+0 and b.ID_B+0 in the explode.

**Comment by ebocher** [comment]
ID is a default column name used by st_explode to add an autonumeric identidiant.
I

**Comment by j3r3m1** [comment]
I have the same trouble if my ID is called "ID_BLABLA" (or whatever actually)

**Comment by ebocher** [comment]
I have found the issue. 
It's related to the metadata.getColumnName() method on ResultSetMetaData
It doesn't return the column alias  e.g ID_A, ID_B. 
Don't know if it's a normal behaviour or linked to H2 jdbc implementation.
@katzyn

**Comment by katzyn** [comment]
This behavior is specified by JDBC, but many drivers violate the requirement. H2 follows the specification here (with exception for some compatibility modes).

Actually you should use `getColumnLabel()` with all drivers.

**Comment by ebocher** [comment]
Thanks @j3r3m1 for reporting this issue
Thanks @katzyn to point me the method
Fixed
