### ISSUE TITLE
Nexus Maven Repository not functional

### ISSUE THREAD

**Issue by ghillert** [orbisgis/h2gis#1201]
It looks like the Maven repo at https://nexus.orbisgis.org/ is empty. Neither are `SNAPSHOT` releases available anywhere (looking for `2.0.0-SNAPSHOT`) nor can you currently build the project from sources.

**Comment by ebocher** [comment]
Sorry but the whole OrbisGIS-H2GIS server has been destroyed during a fire. See https://twitter.com/olesovhcom/status/1369478732247932929
We are on it to build up a new server.

**Comment by ebocher** [comment]
https://nexus.orbisgis.org/ is up !
