### ISSUE TITLE
H2GIS distribution on Jenkins

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1204]
The H2GIS distribution available as a single jar on http://jenkins.orbisgis.org/job/H2GIS/ must be cleaned and rebuild because it contains unnecessary dependencies as apiguardian-api, junit, opentest4j.  moreover, it does not contain the file h2gis-dist-2.0.0XXX.

**Comment by ebocher** [comment]
@SPalominos  any idea ?

**Comment by j3r3m1** [comment]
There is actually no .jar in the .zip file. It only contains the bin.

**Comment by SPalominos** [comment]
Sorry for the late answer, I have repaired the zip which now contains the executable jar. I will update later the packaging in order to remove the useless dependencies.

**Comment by ebocher** [comment]
Nice it 'd be nice to exclude  the jars used to compile the tests (openapi, junit...)

**Comment by ebocher** [comment]
To be done
