### ISSUE TITLE
Impossible to create index on a linked table

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/h2gis#1212]
Hi,
In my current DB called "tataDB", I have linked a table name "toto" from an H2GIS database called "totoDB".
When I try to create index on an integer field on "toto" in "tataDB" it does not work. Here is the error message:
`
[main] ERROR org.orbisgis.orbisdata.processmanager.process.Process - Error while executing the process.
org.h2.jdbc.JdbcSQLFeatureNotSupportedException: Fonctionnalité non supportée: "LINK"
Feature not supported: "LINK"; SQL statement:
CREATE INDEX IF NOT EXISTS TOTO_id ON TOTO USING BTREE(ID); [50100-200]
`

**Comment by ebocher** [comment]
This issue is related to H2 database. I don't know if H2 supports this feature.

**Comment by ebocher** [comment]
CREATE INDEX command is not implemented on a LinkedTable.
https://github.com/h2database/h2database/blob/master/h2/src/main/org/h2/table/TableLink.java#L413
We have to think about it because the update and insert commands are allowed.
Before that, we need to consult  H2 experts : @katzyn , @grandinj, @andreitokar

**Comment by katzyn** [comment]
It isn't possible and shouldn't be possible to create an index on a linked table, because this table belongs to another database. If you need an index on it, it should be created in database that owns this table.

**Comment by j3r3m1** [comment]
Thanks for the answer. Is there a reason why we can insert data or update the linked table but we can not create index ?

**Comment by katzyn** [comment]
Table link cannot detect data modifications performed directly in the database that owns this table.
