### ISSUE TITLE
How can I read geometry in trigger without cast or WKTReader? (How can i unwrap SpatialResultSet in trigger?)

### ISSUE THREAD

**Issue by kunlinyu** [orbisgis/h2gis#1229]
In my application, when some geometry is inserted into one table, I need to use a trigger to create another geometry and insert it into another table. So I create a trigger by:
```java
statement.execute("CREATE` TRIGGER IF NOT EXISTS TRIG_CELLSPACE AFTER INSERT ON cellspace FOR EACH ROW CALL \"indoorsql.core.CellSpaceTrigger\";");
```

and

```java
public class CellSpaceTrigger extends TriggerAdapter {
    public CellSpaceTrigger() {
    }

    @Override
    public void fire(Connection conn, ResultSet oldRow, ResultSet newRow) throws SQLException {
        // SpatialResultSet rs = newRow.unwrap(SpatialResultSet.class);  // <---
        // rs.next();
        // Geometry geom = rs.getGeometry("geom");


        WKTReader reader = new WKTReader();
        Geometry geom;
        try {
            newRow.next();
            geom = reader.read(newRow.getString("geom"));  // workaround
            Statement statement = conn.createStatement();
            statement.execute("INSERT INTO state(geom) VALUES('" + geom.getCentroid().toText() + "')", Statement.RETURN_GENERATED_KEYS);
            ResultSet result = statement.getGeneratedKeys();
            result.next();
            int state_id = result.getInt(1);
            System.out.println(state_id);
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }
}
```
Notice there are three commented lines. That's what I expected. Just like code outside trigger. But I get this:
```bash
Feature not supported: null; SQL statement:
INSERT INTO cellspace(geom) VALUES('POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))'); [50100-197]
org.h2.jdbc.JdbcSQLException: Feature not supported: null; SQL statement:
INSERT INTO cellspace(geom) VALUES('POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))'); [50100-197]
	at app//org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at app//org.h2.message.DbException.get(DbException.java:179)
	at app//org.h2.message.DbException.get(DbException.java:155)
	at app//org.h2.message.DbException.get(DbException.java:144)
	at app//org.h2.tools.SimpleResultSet.getUnsupportedException(SimpleResultSet.java:2274)
	at app//org.h2.tools.SimpleResultSet.unwrap(SimpleResultSet.java:2328)
	at app//indoorsql.core.CellSpaceTrigger.fire(CellSpaceTrigger.java:28)
	at app//org.h2.tools.TriggerAdapter.fire(TriggerAdapter.java:144)
	at app//org.h2.schema.TriggerObject.fireRow(TriggerObject.java:258)
	at app//org.h2.table.Table.fireRow(Table.java:1021)
	at app//org.h2.table.Table.fireAfterRow(Table.java:1011)
	at app//org.h2.command.dml.Insert.insertRows(Insert.java:192)
	at app//org.h2.command.dml.Insert.update(Insert.java:134)
	at app//org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at app//org.h2.command.Command.executeUpdate(Command.java:261)
	at app//org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at app//org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at app//org.h2gis.utilities.wrapper.StatementWrapper.execute(StatementWrapper.java:113)
	at app//indoorsql.core.Consistency.insertCellSpace(Consistency.java:70)
	at app//indoorsql.core.ConsistencyTest.insertCellSpace(ConsistencyTest.java:45)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
So use the uncommented way to read to WKT from ResultSet and use a WKTReader to read it.
I want to ask how can I read geometry objects directly in a trigger?

And one more detailed question: 
I use this connection wrapper outside trigger:
```this.connection = SFSUtilities.wrapConnection(connection);```

what kind of connection will pass to this function?
```public void fire(Connection conn, ResultSet oldRow, ResultSet newRow)```

origin connection or wrapped connection?

**Comment by nicolas-f** [comment]
If you want to use .unwrap(SpatialResultSet.class) you have to wrap the connection with SFSUtilities.wrapConnection

If you use a standard connection you will have to cast the Object to a Geometry.

If you insert geometries, it is faster to use the geometry object than WKT:
```java
PreparedStatement preparedStatement = connection.prepareStatement("INSERT INTO state(geom) VALUES (?)");
preparedStatement.setObject(1, newRow.getObject("geom"));
preparedStatement.execute();
```

You can also use batch if you have a lot of objects to insert.

**Comment by kunlinyu** [comment]
@nicolas-f Thank you! I understand your comment.

I Change the title to "How can I read geometry in a trigger without cast or WKTReader?"

My situation is different from your example. I need to call the ```getCentroid()``` method. So I need a JTS object.

I really want to wrap the connection with SFSUtilities.wrapConnection. But the connection is not created by me.
It is just a parameter pass from h2(not h2gis).

According to https://github.com/h2database/h2database/blob/master/h2/src/main/org/h2/schema/TriggerObject.java#L256, apparently, the connection is a plain connection without any wrap.

I think the reason is: the trigger will be triggered by h2database, not h2gis. so we can not get JTS objects and have to use a WKTReader to parse it?
I'm I correct?

**Comment by nicolas-f** [comment]
You get a JTS Geometry when you do ResultSet.getObject(int columnIndex)

**Comment by kunlinyu** [comment]
@nicolas-f 
I can not do this:
```java
  newRow.getObject("geom").getCentroid();
```
do you mean:
```java
Geometry geom = (Geometry) newRow.getObject("geom");
geom.getCentroid();
```
using a **(Geometry)** to cast the non-type object to Geometry typed object?

**Comment by nicolas-f** [comment]
Yes in java you have to do the cast from Object to Geometry

**Comment by kunlinyu** [comment]
Thank you.
