### ISSUE TITLE
Improve ShapeFile driver

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1233]
The read method of the ShapeFile driver, convert bytes to a JTS geometry and then convert the geometry to H2 ValueGeometry.
We can short cut it and convert directly the bytes to H2 ValueGeometry.

See https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/io/shp/internal/SHPDriver.java#L245

**Comment by ebocher** [comment]
Looking at the ValueGeometry, we can see that the geometry is parsed too many times.
Here a test

```
 WKTReader wktReader = new WKTReader();
        Geometry geom = wktReader.read("POINT(0 10)");
        ValueGeometry.getFromGeometry(geom);
```
JTSUtils.parseGeometry(g, target) is used in getFromGeometry to build EnvelopeAndDimensionSystemTarget

It is used for a second time when JTSUtils.geometry2ewkb is called to build the new ValueGeometry.

See https://github.com/h2database/h2database/blob/master/h2/src/main/org/h2/value/ValueGeometry.java#L85


I propose to reduce the number of iterations with a new method that creates the byte array from geometry.
@katzyn

**Comment by katzyn** [comment]
I don't remember why I wrote code in that way, but most likely it wasn't possible to determine dimension system of `Geometry` without scanning over all its points. JTS was very buggy in those times.

**Comment by ebocher** [comment]
It seems that since JTS 1.16 the dimension has been fixed on JTS.

```
1.16
Added XYZM support to CoordinateSequence and CoordinateSequenceFactory with getDimension() and getMeasures() information
1.16.0-RC1
Added XYZM support to CoordinateSequence and CoordinateSequenceFactory with getDimension() and getMeasures() information.
```
What is the minum JTS version for H2 ?

**Comment by katzyn** [comment]
1.17

**Comment by ebocher** [comment]
Note that JTS always supports z coordinates with NaN values. So if a geometry returned for example by a function is a 3D POINT
with NaN it will be set a dimension = 3 from JTS and cause incompatibility with H2 which is more restrictive.

**Comment by katzyn** [comment]
In that case this additional scan is still needed.

**Comment by ebocher** [comment]
Yes I think so but we can limit the number of scan because geometry can have a large number of coordinates.

**Comment by ebocher** [comment]
I can investigate

**Comment by katzyn** [comment]
Please note that H2 intentionally validates (very basic) correctness of geometry. If first point has coordinates `(0 0 NaN)` and some other point has coordinates `(0 0 0)` we need to throw an exception.

**Comment by katzyn** [comment]
Hypothetically this logic can be moved to EWKB output target, but it can make it a little bit slower for other operations.

**Comment by ebocher** [comment]
I will check the standards ISO and OGC, plus PostGIS before any changes.

**Comment by katzyn** [comment]
There is no NaNs is the standards.

**Comment by ebocher** [comment]
Tested with POSTGIS 3.1 and H2GIS master

POSTGIS

```
SELECT ST_AsText(ST_MakePoint('NaN', 'NaN'));
-> POINT(NaN NaN)
```
H2GIS

```
SELECT ST_AsText(ST_GeomFromText('POINT(Nan Nan)'));
->  POINT EMPTY
```

**Comment by ebocher** [comment]
POSTGIS

```
SELECT st_coorddim(ST_MakePoint('NaN', 'NaN',  'NaN'))

-> 3

```
H2GIS

```
SELECT st_coorddim(ST_GeomFromText('POINT(Nan Nan Nan)'));
->  2
```

JTS
```
-> 3
```

**Comment by katzyn** [comment]
First of all, `POINT (NaN NaN)` is not a valid WKT.

Because WKB doesn't have any representation for `POINT EMPTY`, it is encoded as a normal point, but with all `NaN` values as suggesed in https://www.geopackage.org/spec
> If the geometry is a Point, it SHALL be encoded with each coordinate value set to an IEEE-754 quiet NaN value. GeoPackages SHALL use big endian 0x7ff8000000000000 or little endian 0x000000000000f87f as the binary encoding of the NaN values. (This is because Well-Known Binary as defined in OGC 06-103r4 [I9] does not provide a standardized encoding for an empty point set, i.e., 'Point Empty' in Well-Known Text.)

If some software reads this encoding as `POINT(NaN NaN)`, it is a bug of that software.

**Comment by ebocher** [comment]
This is the geopackage spec and interpretation.  Investigation is necessary.

**Comment by katzyn** [comment]
This specification only extends WKB and provides a way to write `POINT EMPTY`, just like EWKB extends WKB and provides a way to write SRID into it.

In OGC 06-103r4 there are no NaNs and infinities. It means they are invalid and we're not going to support invalid geometries on H2 side.

---

I tested this double-scan in `ValueGeometry`. For a large multipoint first scan takes only about 13% of time in this method. It means we can't optimize this method significantly.

**Comment by ebocher** [comment]
> This specification only extends WKB and provides a way to write `POINT EMPTY`, just like EWKB extends WKB and provides a way to write SRID into it.

Sorry but your are talking about Geopackage ? If yes.  Geopackage is a spec for a specfic db encoding, sqllite. Geopackage doesn't define wkb encoding rule for all spatial db. I'm prety sure that Maria DB works as PostGIS. But you are also right there is a lack of precise definition for WKB encoding. 
Generally I trust PostGIS which is one of the oldest and most important community in spatial databases.
The main problem I see with H2 is that it transforms the input data of the geometries by omitting NaN value. For me, if the NaN value exists it is to represent something.

How many points ? What about complex geometry collection with many polygons and holes ?

**Comment by katzyn** [comment]
H2 uses OGC 06-103r4 as a reference document about WKT and overall structure of geometries.
H2 additionally supports SRID.

Nobody cares how we encode POINT EMPTY in H2 internally, H2 uses the encoding from GeoPackage because there are no better ideas. Earlier it wasn't possible to store POINT EMPTY in H2. PostGIS also used that encoding, BTW. Maybe they use something different now, I tested it a long time ago.

OGC 06-103r4 doesn't have non-finite values, that's why H2 doesn't have them too.

Do you still need to have possibility to use `'POINT (1 2 3)'` in literals in H2 with invalid WKT? To speed up their parsing it will be better to disallow them and allow only `'POINT Z (1 2 3)'`.

**Comment by ebocher** [comment]
MARIADB 10.5.13

```
SELECT ST_ASTEXT(POINT(10, 0, 'NaN')
or
SELECT ST_ASTEXT(ST_GEOMFROMTEXT('POINT(nan 0)'));
-> null
```
Because MARIADB doesn't support z and m value
https://mariadb.com/kb/en/geometry-types/


MSSQL

supports Z, M measures
https://docs.microsoft.com/en-us/sql/relational-databases/spatial/point?view=sql-server-ver15
No way to test it

**Comment by katzyn** [comment]
> Do you still need to have possibility to use `'POINT (1 2 3)'` in literals in H2 with invalid WKT? To speed up their parsing it will be better to disallow them and allow only `'POINT Z (1 2 3)'`.

Could you answer this question? I'm trying to optimize dimension system scan.

**Comment by ebocher** [comment]
Just to complete the doc

SPATIALITE SQLite version 3.35.5 is based on GEOS version 3.9.0-CAPI-1.16.2

So it must work as PostGIS but SPATIALITE has it's own function to encode in GPKG.
See gpkgMakePointZ -> https://www.gaia-gis.it/gaia-sins/spatialite-sql-4.2.0.html

**Comment by ebocher** [comment]
> H2 uses OGC 06-103r4 as a reference document about WKT and overall structure of geometries. H2 additionally supports SRID.

> Nobody cares how we encode POINT EMPTY in H2 internally,

Noboby ? not the H2GIS users ;-)

> H2 uses the encoding from GeoPackage because there are no better ideas. Earlier it wasn't possible to store POINT EMPTY in H2. PostGIS also used that encoding, BTW. Maybe they use something different now, I tested it a long time ago.

 I am more confident in PostGIS than GPKG due to their long experience in spatial data. 
POINT EMPTY has been removed since 2015/10/07 in PostGIS
See https://git.osgeo.org/gitea/postgis/postgis/src/tag/3.2.0beta3/NEWS
 - #3181, POINT EMPTY is now stored as POINT(NaN NaN) in WKB, instead of as MULTIPOINT EMPTY

**Comment by ebocher** [comment]
> Could you answer this question? I'm trying to optimize dimension system scan.

I don't understand why you want to add a patch. I think the best way will be to follow JTS.
JTS is most popular, robust geometry library and It would be better not to make specific developments in H2 that are complicated to maintain. This is my point of view ;-)

Maybe I forgot something,

**Comment by katzyn** [comment]
This syntax (with missing Z in 3D-geometry) was accepted due to bug in old version of JTS. Is it still needed?

**Comment by ebocher** [comment]
> This syntax (with missing Z in 3D-geometry) was accepted due to bug in old version of JTS. Is it still needed?

Let's me check JTS 1.17

**Comment by katzyn** [comment]
It either writes `POINT (1 1)` or `POINT Z(1 1 1)` depending on its argument.

In some old version it produced `POINT (1 1 1)`.

**Comment by ebocher** [comment]
Note that POINT (1 1 Nan) will return a 3D geometry as PostGIS does

**Comment by ebocher** [comment]
By the way, what about supporting JTS > 1.18 because there are too many improvements and H2 2.0.X is for a new age ;-)

**Comment by katzyn** [comment]
H2 should be able to work with JTS 1.18 too, but if it doesn't work we can bump our requirements to 1.18.

**Comment by katzyn** [comment]
I tested 1.18.2, it has the same bugs as 1.17.0. For example, when `WKTReader` reads `LINESTRING EMPTY` it constructs a coordinate sequence with three dimensions instead of 2.

It means we still can't detect number of dimensions in empty geometries from JTS.

**Comment by ebocher** [comment]
Do you have a unit or pseudo code to share ?

**Comment by ebocher** [comment]
GEOS returns 2 as dimension.
I will push an issue on JTS

**Comment by ebocher** [comment]
humm

```
WKTReader wktReader = new WKTReader();
POLYGON geom = (POLYGON) wktReader.read("POLYGON EMPTY");
 geom.getCoordinateSequence().getDimension()
```
returns 1

**Comment by ebocher** [comment]
https://github.com/locationtech/jts/issues/827

**Comment by katzyn** [comment]
OK, H2 will use the declared number of dimensions and measures for empty points, line strings, and polygons from JTS. It means `WKTReader.setIsOldJtsCoordinateSyntaxAllowed(false)` may be needed.

But empty collections of all four supported types from JTS with still be assumed as XY-only until JTS will be improved to preserve the dimension system in their properties.

**Comment by katzyn** [comment]
Could you test H2 compiled from the current sources? I rewrote code that checks dimension system for JTS `Geometry`, EWKB and EWKT representations (GeoJSON still uses old method with two scans) and I also implemented detection of dimension system for empty points, line strings, and polygons from JTS.

**Comment by ebocher** [comment]
I'm on it but I need to update H2GIS due to change on
```
 public boolean lock(SessionLocal session, boolean exclusive,
                        boolean forceLockEvenInMvcc) {
    }
```

**Comment by ebocher** [comment]
@katzyn 
With the last change  'POLYGON ((0 0 0, 2 0 0, 1 1 0, 0 0 0))'::GEOMETRY is no supported even if JTS parser support it. Right ?
We must used POLYGON Z.

**Comment by katzyn** [comment]
Yes, `POLYGON Z` should be used (and properly configured `WKTReader` also requires that).
