### ISSUE TITLE
H2 Version 2

### ISSUE THREAD

**Issue by dirkoberhaus** [orbisgis/h2gis#1235]
Hi,

is the support of version 2 of H2 on the roadmap of h2gis?

Kind regards

Dirk

**Comment by ebocher** [comment]
This is already done on the master. Here are now testing it. We hope to release asap

**Comment by kunlinyu** [comment]
@ebocher How is everything going?What do you mean "testing"? Run some tests or add more unit tests code?

**Comment by kunlinyu** [comment]
@ebocher 
How is everything going?
What features lack testing for now? If you share a feature list that lacks testing, it is my horner to do the test or add auto-run unit tests for them.

**Comment by SPalominos** [comment]
Thank you for the proposition, the migration to h2 2.0.202 is technically done, and we are migrating to 2.0.204. As h2 may have some other fix to do, we are waiting before releasing H2GIS. But you can use the SNAPSHOT version meanwhile if you want.

**Comment by ebocher** [comment]
We are working on a new module in H2GIS to run a set of complex SQL scripts with spatial functions to ensure H2GIS robustness. We plan to release H2GIS when this module is finished.

**Comment by beikov** [comment]
With H2 2.1.210 now out, can you give us an estimate for this? :)

We use H2GIS in Hibernate Spatial for testing and desperately need a H2GIS version compatible with H2 2+ so we can update our version.

**Comment by ebocher** [comment]
We are on it . See  : https://github.com/orbisgis/h2gis/pull/1246
We are waiting the release on maven : https://mvnrepository.com/artifact/com.h2database/h2

**Comment by beikov** [comment]
It's on Maven Central already, the UI cache is simply not up-to-date yet.

**Comment by ebocher** [comment]
Thanks I will check it.

**Comment by beikov** [comment]
I suppose the PR merge means you will be doing a release soon? :)

**Comment by ebocher** [comment]
We will run H2GIS 2.0 master with a set of SQL scripts to be sure that everything is ok.
I hope that we will be able to release before the end of the week.

**Comment by ebocher** [comment]
I am closing this issue because we are on the road to release H2GIS very very soon.
