### ISSUE TITLE
Migration to H2 2.0.206

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1236]
To be checked : 

- [x] https://github.com/h2database/h2database/issues/3251

**Comment by katzyn** [comment]
I think you can skip H2 2.0.202 and require H2 2.0.4 in H2GIS 2.0.

**Comment by ebocher** [comment]
Thanks I will test it

**Comment by ebocher** [comment]
Since H 2.0.204 returns more information on the geometry column e.g GEOMETRY(POINT, SRID) instead of only GEOMETRY 
we must updated all H2GIS functions that query the ResulsetMedata

**Comment by ebocher** [comment]
Migration to 2.0.204 done.
We are now testing it with a set of SQL scripts

**Comment by ebocher** [comment]
Migration done but there is a new issue with linked table
https://github.com/h2database/h2database/issues/3322

**Comment by katzyn** [comment]
H2 2.0.206 was published.

**Comment by ebocher** [comment]
Thanks

**Comment by ebocher** [comment]
Done
