### ISSUE TITLE
Should I create spatial indices explicitly?

### ISSUE THREAD

**Issue by kunlinyu** [orbisgis/h2gis#1237]
I read the document "spatial-indices":
http://www.h2gis.org/docs/1.5.0/spatial-indices/
or source code of the document:
https://github.com/orbisgis/h2gis/blob/02ce966c02b650d33b6f639e78263b10895c02fc/docs/dev/getting-started/spatial-indices.md?plain=1#L27

This example creates the spatial indices explicitly.
But even if I do not create spatial indices for the geometry column of my table, everything goes well.

So I want to confirm whether I should create spatial indices explicitly or leave them implicitly?

P.S.
The document above mentioned spatial operator "&&"
"(such as the && predicate operator for bounding box overlap)"
But I can not find any document about it (besides operator with the prefix "ST_")
Where can I find operator document about "&&" and more?

**Comment by nicolas-f** [comment]
This is not specific to H2GIS but only related to H2.

https://www.h2database.com/html/advanced.html#spatial_features

You don't have to create a spatial index however it is highly recommended if you want to reduce the time required to filter results on this table using spatial queries.

Currently the only method to use the spatial index is the usage of the operator **&&**

**Comment by ebocher** [comment]
Thanks  @nicolas-f for the comment ;-)
