### ISSUE TITLE
Automatic release asset

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/h2gis#1259]
On the workflow `CI Release` a step should be added to upload the `h2gis-dist` zip on the Github release assets.

**Comment by ebocher** [comment]
jar or zip file ?

**Comment by SPalominos** [comment]
You're right, the `zip` file.

**Comment by ebocher** [comment]
@SPalominos  Any plan ?

**Comment by SPalominos** [comment]
Done, the snapshot archive issue is discussed at #1219
