### ISSUE TITLE
TableLocation and DBType

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/h2gis#1264]
We could add the following signature for the `TableLocation` constructor :
- `new TableLocation(String table, DBType dbType)`
- `new TableLocation(String schema, String table, DBType dbType)`
- `new TableLocation(String catalog, String schema, String table, DBType dbType)`

**Comment by ebocher** [comment]
- `new TableLocation(String catalog, String schema, String table, DBType dbType)` 
exits see :  https://github.com/orbisgis/h2gis/blob/master/h2gis-utilities/src/main/java/org/h2gis/utilities/TableLocation.java#L59

I will implement others
