### ISSUE TITLE
Remove OrbisParent pom dep

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1289]
OrbisParent pom is used to manage all deps.  I wonder if H2GIS should not be independant from OrbisParent to simplify the releases.

**Comment by nicolas-f** [comment]
I should not have created OrbisParent in the past. It was created originally only to share the remote repository configuration.
Now its quite cumbersome to make a release and its a weird external dependency. (another repo)

**Comment by SPalominos** [comment]
But it makes also a lot easier to share maven build/plugins configuration and profiles, to synchronize dependencies version and to lighten the children project poms.

**Comment by ebocher** [comment]
Done
