### ISSUE TITLE
Mixed SRID behavior in ST_DISTANCE vs. ST_DISTANCESPHERE

### ISSUE THREAD

**Issue by apano-on** [orbisgis/h2gis#1292]
ST_DISTANCE and ST_DISTANCESPHERE exhibit different behavior when inputs with mixed SRIDs are provided:

ST_DISTANCE --> SQLException("Operation on mixed SRID geometries not supported"). See [here](https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_Distance.java#L59)
ST_DISTANCESPHERE --> null. See [here](https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_DistanceSphere.java#L62).

Shouldn't the behavior be consistent? In particular the error for ST_DISTANCE is more informative, while for ST_DISTANCESPHERE it is not very informative. I do not know if there is any official guideline or recommendation.

**Comment by ebocher** [comment]
Thanks for reporting.
ST_DISTANCESPHERE must have the same behaviour than ST_DISTANCE

**Comment by ebocher** [comment]
Fixed thanks
