### ISSUE TITLE
SHPWrite with empty geom

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#1313]
Hi,

I'm using NoiseModelling v4.0.0 in with H2GIS 2.1

```xml
<jts-io-version>1.18.2</jts-io-version>
<h2-version>2.1.210</h2-version>
<h2gis-version>2.1.0-SNAPSHOT</h2gis-version>
<cts-version>1.6.0</cts-version>
```

I have a table of buildings (coming from OSM [BBBike](https://extract.bbbike.org/)), in which there is 
- 187 geom
- 6 empty geom (detected with `ST_IsEmpty`)

![buildings_dbeaver](https://user-images.githubusercontent.com/1871248/175019717-41c695b9-561e-4c3e-9354-7120406957f0.png)

When I export this table into SHP, I have a problem : starting from the first empty geom, all the building geometries becomes empty

```sql
CALL SHPWRITE ('/home/gpetit/BUILDINGS.shp','BUILDINGS')
```
I can open the shp in QGIS, but all the "empty" geometry are not visible on the map (below, only the 9 yellow selected buildings are visible -  the rest are well listed, with all their attributes in the table)

![buildings_qgis](https://user-images.githubusercontent.com/1871248/175019875-8722d1b0-9549-4da0-b1c3-43c0470dc8a3.png)

In parallel, if I try to load the shp into the H2GIS db,

```sql
CALL SHPREAD ('/home/gpetit/BUILDINGS.shp','BUILDINGS2')
```

It returns
```
SQL Error: INSERT INTO BUILDINGS2 VALUES (?, ?, ?, ? )
Index 0 out of bounds for length 0; SQL statement:
CALL SHPREAD ('/home/gpetit/BUILDINGS.shp','BUILDINGS2') [0-210]
```

**Comment by ebocher** [comment]
Thanks !
We must check the shp spec to see if it can support empty geometry.
Here a unit test for H2GIS

```
@Test
    public void exportImportEmptyGeometry() throws SQLException {
        Statement stat = connection.createStatement();
        stat.execute("DROP TABLE IF EXISTS GEOTABLE");
        stat.execute("create table GEOTABLE(idarea int primary key, the_geom GEOMETRY(POINT))");
        stat.execute("insert into GEOTABLE values(1, 'POINT (0 0)'::GEOMETRY),(2, 'POINT EMPTY'::GEOMETRY);");
        // Create a shape file using table area
        stat.execute("CALL SHPWrite('target/points_withempty.shp', 'GEOTABLE', true)");
        stat.execute("CALL SHPRead('target/points_withempty.shp', 'IMPORT_GEOTABLE')");
        ResultSet res = stat.executeQuery("SELECT THE_GEOM FROM IMPORT_GEOTABLE ORDER BY idarea;");
        res.next();
        assertGeometryEquals("POINT(0 0)", res.getObject(1));
        res.next();
        assertTrue( ((Geometry)res.getObject(1)).isEmpty());
        res.close();
    }
```

**Comment by gpetit** [comment]
Cool thx boss !
