### ISSUE TITLE
Add ST_Project

### ISSUE THREAD

**Issue by dVeon-loch** [orbisgis/h2gis#1324]
It would be useful if H2GIS had ST_Project(geography g1, float distance, float azimuth); to do the following:
Returns a point projected from a start point along a geodesic using a given distance and azimuth (bearing). This is known as the direct geodesic problem.

See https://postgis.net/docs/ST_Project.html for more details.

**Comment by ebocher** [comment]
Note that H2GIS doesn't support geography type.
By the way, feel free to send a PR to support this feature.

**Comment by ebocher** [comment]
Done here #1361
