### ISSUE TITLE
Update to H2 2.2.222

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1358]
See

https://github.com/h2database/h2database/issues/3877 and

https://github.com/h2database/h2database/releases/tag/version-2.2.222

**Comment by ebocher** [comment]
Waiting for deployment  on https://repo1.maven.org/maven2/com/h2database/h2/

**Comment by katzyn** [comment]
You can skip 2.2.222 and upgrade directly to 2.2.224.

**Comment by ebocher** [comment]
Thanks @katzyn

**Comment by ebocher** [comment]
Done
