### ISSUE TITLE
Trouble reading SHP file

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/h2gis#1379]
Hi,
When I try to read some shapefile, the same error message as in this issue (#1374) is displayed.

The data :
[data_test.zip](https://github.com/orbisgis/h2gis/files/15147545/data_test.zip)

Any idea if this can come from the same problem as in the other issue ?

**Comment by j3r3m1** [comment]
OK I did not know about the .cpg file containing the information about encoding. Is there a way to automatically read the file with the right encoding using the SHPREAD function ?

**Comment by nicolas-f** [comment]
Hi,

no the current version of h2gis assume that the dbf file is in utf8 encoding.

**Comment by ebocher** [comment]
See #1381

**Comment by ebocher** [comment]
Fixed
