### ISSUE TITLE
Read and Write CPG file for dbf string encoding

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis#1380]
.cpg — used to specify the [code page](https://en.wikipedia.org/wiki/Code_page) (only for .dbf) for identifying the [character encoding](https://en.wikipedia.org/wiki/Character_encoding) to be used {content-type: text/plain OR x-gis/x-shapefile }

**Comment by nicolas-f** [comment]
About #1379

**Comment by ebocher** [comment]
See #1381

**Comment by ebocher** [comment]
Fixed
