### ISSUE TITLE
Manage SRID on empty geometry

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1385]
H2GIS checks the SRID of the geometries to allow some operations.
This cause some troubles when a geometry is empty because the SRID is unhnown. 

See : https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/spatial/operators/ST_Intersection.java#L61

```
Select ST_SRID('POINT EMPTY'::GEOMETRY) as the_geom
```
returns a null value but it must return a 0 srid

```
Select st_intersects('POINT EMPTY'::GEOMETRY , 'POINT(0 0)'::geometry) as the_geom

```
throws an exception. It woud be more accurate to return  POINT EMPTY

**Comment by ebocher** [comment]
@nicolas-f

**Comment by nicolas-f** [comment]
```sql
Select st_intersects('POINT EMPTY'::GEOMETRY , 'POINT(0 0)'::geometry) as the_geom
```
Maybe it should return false because it is not in the same projection system

**Comment by ebocher** [comment]
Fixed
