### ISSUE TITLE
ST_Extent say mixed SRID error if one geometry is empty

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis#1400]
In the aggregate function if the geometry is empty it set the srid to 0.

So instead of ignoring the empty geometry it raise an error with the message "Operation on mixed SRID geometries not supported" 

https://github.com/orbisgis/h2gis/blob/v2.2.3/h2gis-functions/src/main/java/org/h2gis/functions/spatial/properties/ST_Extent.java

We should ignore the geometry if it is empty, without raising an error.

**Comment by ebocher** [comment]
Sure !

**Comment by ebocher** [comment]
Yes please my friend. I'm full

**Comment by ebocher** [comment]
Fixed
