### ISSUE TITLE
Geopackage format support

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis#24]
Write a driver for ogc geopackage format

**Comment by nicolas-f** [comment]
We could use http://sqljet.com and write a new table engine. Thanks to that H2GIS could remain 100% java and handle geopackage format.

**Comment by ebocher** [comment]
Seems interesting https://github.com/ngageoint/geopackage-java

**Comment by gpetit** [comment]
We may need to export from H2GIS db to geopackage for the Plamade project.
Any input concerning the development of this driver ?
@ebocher

**Comment by ebocher** [comment]
No plan. 
Is this issue blocking for Plamade project ?
If yes it could be nice to work with @SPalominos

**Comment by gpetit** [comment]
Ok.
It seems that UE is asking to have the resulting data in this format.
So if we are not able to develop this driver, we (or colleagues from Cerema) will have to find a 'manual' work around

**Comment by nicolas-f** [comment]
Its not a little feature. There is months worth of work so using third party program to generate this should be more efficient.
