### ISSUE TITLE
DAE Collada format support

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis#412]
Add support for writing DAE files in order to import extruded geometry into sketch-up.

**Comment by ebocher** [comment]
Is it necessary ?

**Comment by nicolas-f** [comment]
This is the only way to export properly in SketchUp as it only support KMZ files with geometry inside in DAE format.

**Comment by ebocher** [comment]
Is it necessary ?

**Comment by nicolas-f** [comment]
If no ones need it we can close this issue
