### ISSUE TITLE
Add web documentation for ST_Tessellate

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#530]
Create the documentation for ST_Tessellate (see #419) and https://github.com/orbisgis/h2gis/blob/master/h2spatial-ext/src/main/java/org/h2gis/h2spatialext/function/spatial/mesh/ST_Tessellate.java

@gpetit

**Comment by ebocher** [comment]
@gpetit  Could you please write this doc ?

**Comment by ebocher** [comment]
@gpetit  thanks
