### ISSUE TITLE
Bug in ST_LineIntersector (or documentation to improve)

### ISSUE THREAD

**Issue by obonin** [orbisgis/h2gis#535]
ST_LineInterstor does not behave like ST_Split:
select ST_LineIntersector('LINESTRING(0 3, 3 3, 6 3)', 'LINESTRING(1 3, 3 3)');
does not split the line in (3 3) whereas
select ST_Split('LINESTRING(0 3, 3 3, 6 3)', 'LINESTRING(1 3, 3 3)');
works as intended.

Either this is a bug in ST_LineInterstector, or the documentation should be more explicit about what is an intersection.
Thanks!

**Comment by ebocher** [comment]
Thanks. I will look on it asap.

**Comment by nicolas-f** [comment]
In your sample you don't look to compute intersection points but exploding linestring into segments. The appropriate function is [ST_ToMultiSegments](http://www.h2gis.org/docs/dev/ST_ToMultiSegments/)

**Comment by nicolas-f** [comment]
As a side note. You can after use [ST_LineMerge](http://www.h2gis.org/docs/dev/ST_LineMerge/) in order to reduce the graph nodes.

**Comment by ebocher** [comment]
ST_LineIntersector produces a valid result. It returns a multilinestring with 3 lines

```java
MULTILINESTRING ((0 3, 1 3), (1 3, 3 3), (3 3, 6 3))
```

because the LINESTRING(1 3, 3 3) overlaps the 'LINESTRING(0 3, 3 3, 6 3)

**Comment by obonin** [comment]
My mistake, the example was supposed to be

select ST_LineIntersector('LINESTRING(0 3, 3 3, 6 3)', 'LINESTRING(3 0, 3 3)');
vs
select ST_Split('LINESTRING(0 3, 3 3, 6 3)', 'LINESTRING(3 0, 3 3)');

I have mixed up the coordinates. The lines weren't supposed to overlap, but to be touching by only one point.

Both examples give the same results (as intended). They aren't able to reproduce the problem I have encountered on real world data: cases when ST_LineIntersector does not work for objects that intersect by touching (and correct behavior for ST_Split). I will try to isolate such a problem.

**Comment by obonin** [comment]
The problem is the following:

select ST_LineIntersector('LINESTRING (773869.3099999997 6359672, 773681.8799999997 6359617, 773516.6899999997 6359722, 773300.3099999997 6359528.5, 772634.3099999997 6359395, 772459.5599999997 6359715, 772590.2499999997 6360364, 772177.8799999997 6360270, 771791.4399999997 6360541.5, 771776.6899999997 6360255.5, 771733.3099999997 6360167, 771464.1899999997 6360055, 771384.8099999997 6359670.5)', 'LINESTRING (770900 6360800, 771791.4399999997 6360541.5)');

gives the same correct result as

select ST_Split(‘LINESTRING (773869.3099999997 6359672, 773681.8799999997 6359617, 773516.6899999997 6359722, 773300.3099999997 6359528.5, 772634.3099999997 6359395, 772459.5599999997 6359715, 772590.2499999997 6360364, 772177.8799999997 6360270, 771791.4399999997 6360541.5, 771776.6899999997 6360255.5, 771733.3099999997 6360167, 771464.1899999997 6360055, 771384.8099999997 6359670.5)', 'LINESTRING (770900 6360800, 771791.4399999997 6360541.5)');

but 

select ST_LineIntersector('LINESTRING (773869.3099999997 6359672, 773681.8799999997 6359617, 773516.6899999997 6359722, 773300.3099999997 6359528.5, 772634.3099999997 6359395, 772459.5599999997 6359715, 772590.2499999997 6360364, 772177.8799999997 6360270, 771791.4399999997 6360541.5, 771776.6899999997 6360255.5, 771733.3099999997 6360167, 771464.1899999997 6360055, 771384.8099999997 6359670.5)', ST_ACCUM(ST_MAKELINE(ST_STARTPOINT('LINESTRING (770900 6360800, 771791.4399999997 6360541.5)'), ST_LOCATEALONG('LINESTRING (770900 6360800, 771791.4399999997 6360541.5)', 1.1, 0))));

does not work. The second (short) line touches the first line in (771791.4399999997 6360541.5).

**Comment by nicolas-f** [comment]
Your line doesn't intersects:
```sql
select st_intersects('LINESTRING (773869.3099999997 6359672, 773681.8799999997 6359617, 773516.6899999997 6359722, 773300.3099999997 6359528.5, 772634.3099999997 6359395, 772459.5599999997 6359715, 772590.2499999997 6360364, 772177.8799999997 6360270, 771791.4399999997 6360541.5, 771776.6899999997 6360255.5, 771733.3099999997 6360167, 771464.1899999997 6360055, 771384.8099999997 6359670.5)',ST_MAKELINE(ST_STARTPOINT('LINESTRING (770900 6360800, 771791.4399999997 6360541.5)'), ST_LOCATEALONG('LINESTRING (770900 6360800, 771791.4399999997 6360541.5)', 1.1, 0))) intersects;
-- Give False
```

This is precision issue in JTS. You have to find another approach for your processing.

**Comment by obonin** [comment]
Its actually does intersect however. If I dilate a little more the short line (by 1.2 rather than by 1.1) it works:

select st_intersects('LINESTRING (773869.3099999997 6359672, 773681.8799999997 6359617, 773516.6899999997 6359722, 773300.3099999997 6359528.5, 772634.3099999997 6359395, 772459.5599999997 6359715, 772590.2499999997 6360364, 772177.8799999997 6360270, 771791.4399999997 6360541.5, 771776.6899999997 6360255.5, 771733.3099999997 6360167, 771464.1899999997 6360055, 771384.8099999997 6359670.5)',ST_MAKELINE(ST_STARTPOINT('LINESTRING (770900 6360800, 771791.4399999997 6360541.5)'), ST_LOCATEALONG('LINESTRING (770900 6360800, 771791.4399999997 6360541.5)', 1.2, 0))) intersects;

I have found a different means to compute the same thing.
