### ISSUE TITLE
CityGML importer - exporter

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#554]
It would be nice to user the CityGML4J library to import an export City GML file in H2GIS.

https://github.com/citygml4j/citygml4j

**Comment by ebocher** [comment]
It seems that H2 is already used.
https://github.com/3dcitydb/importer-exporter

**Comment by nicolas-f** [comment]
It use JAXB https://github.com/3dcitydb/importer-exporter/blob/master/src/org/citydb/modules/citygml/importer/controller/Importer.java

**Comment by nicolas-f** [comment]
Why this enhancement has been closed ?
