### ISSUE TITLE
New functions documentation

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#559]
- [x] ST_GeomFromWKB 
- [x] ST_AsGML
- [x] ST_GeomFromGML
- [x] ST_GeomFromGeoJSON
- [x] ST_OSMMapLink
- [x] ST_GoogleMapLink

**Comment by ebocher** [comment]
@gpetit waiting some documentation.

**Comment by ebocher** [comment]
- [ ] TSVRead
- [ ] TSVWrite

**Comment by ebocher** [comment]
@gpetit  could you plan this document for the 1.3.0 ?

**Comment by gpetit** [comment]
Yes ... I have to note it in my todo list ;-)

**Comment by ebocher** [comment]
thanks

**Comment by ebocher** [comment]
- [ ] ST_OSMDownloader(GEOMETRY, VARCHAR path of the file, BOOLEAN delete file if exists );

**Comment by ebocher** [comment]
- [ ] ST_NumInteriorRing(s) functions must be updated with : 

Return the number of interior rings of the first polygon in the geometry. This will work with both POLYGON and MULTIPOLYGON.Return NULL if there is no polygon in the geometry.
