### ISSUE TITLE
h2gis, postgis st_transform

### ISSUE THREAD

**Issue by ackerball** [orbisgis/h2gis#562]
i use postgis and h2gis and i have tested ST_Transform function on both systems:

SELECT  ST_AsText(ST_Transform(
ST_GeomFromText('POINT(5873455.6 445588.07)',25833),4326)
)
on postgis i get the following result

POINT(58.4155109850716 2.92774013845001)

on h2gis

POINT (58.454757350381854 2.9198520253289484)

different coordinates with the same statement.

Could someone explain the difference or what went wrong ?

**Comment by gpetit** [comment]
Hi @ackerball and thanks for this feedback.

H2GIS is using CTS library (see https://github.com/orbisgis/cts) while PostGIS is using Proj4. So the problem should be in this difference.

We'll try to investigate asap.

Regards

Gwendall

**Comment by ackerball** [comment]
hello gwendall,

i've got some support from here 
(http://gis.stackexchange.com/questions/152073/h2gis-and-postgis)
so i have to swap lat long coordinates and then i get the right results on both systems.

i will close this issue.

thanx

frank

**Comment by gpetit** [comment]
Perfect !

Thanks Frank
