### ISSUE TITLE
Error message "Column _ROWID_ does not exists"

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/h2gis#563]
I have the following error message when I click on a row of one of my table : "Column _ROWID_ does not exists". It is also impossible to zoom in on the row selected. No message appear but nothing happen on the "Map Editor".

I use OrbisGIS 5.1.0 and my table does not contain a primary key, only a geometry column.

**Comment by ebocher** [comment]
Issue related to OrbisGIS  https://github.com/orbisgis/orbisgis/issues/840
