### ISSUE TITLE
GeoRaster datatype

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#570]
Implement a new datatype to support georaster data.

The georaster datatype must be based on the WKTRaster model. http://postgis.net/docs/manual-2.1/RT_reference.html

The georaster datatype must be an interface to offer a way to plug others libraries or models.

**Comment by nicolas-f** [comment]
Done

**Comment by nicolas-f** [comment]
TODO GeoRasterRendered image that claim to have tileSupport. Size of tile is the same of WKBRasterDataBuffer pixel cache (width x 1)

**Comment by ebocher** [comment]
Yes good catch because some JAI operators need adaptive pixel cache.
