### ISSUE TITLE
Fill sink algorithm

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#577]
Implement an efficient algorithm to fill all sinks in a DEM.

References

http://www.cs.duke.edu/geo*/terraflow/papers/journal_terraflow.pdf

http://www.cs.duke.edu/geo*/terraflow/papers/alenex00_drainage.ps.gz

http://www.researchgate.net/publication/240407597_A_fast_simple_and_versatile_algorithm_to_fill_the_depressions_of_digital_elevation_models._CATENA -> used by GDBMS

**Comment by nicolas-f** [comment]
SQL signature
FixedDem ST_FillSink(Dem, maxDepth, minSlope) ?

maxDepth : https://github.com/orbisgis/grap/blob/master/src/main/java/org/grap/processing/operation/hydrology/OpFillSinks.java#L286

**Comment by ebocher** [comment]
Don't know and I think user is not able to understand this parameter.

**Comment by nicolas-f** [comment]
then go to hidden default value ?

**Comment by nicolas-f** [comment]
minslope was required on gdms ST_FillSinks

**Comment by ebocher** [comment]
yes minslope

**Comment by nicolas-f** [comment]
ST_FillSinks(The_Raster raster, MinSlope float)
