### ISSUE TITLE
GeoRaster processing API

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#578]
The JAI-EXT library will be used to develop the georaster algorithms. 
See https://github.com/geosolutions-it/jai-ext.

This library must be tested with the https://github.com/jai-imageio/jai-imageio-core because It's fully compliant with the JAI-EXT  and the H2GIS licences.

**Comment by nicolas-f** [comment]
What about ```ST_MapAlgebra```

What do you think about https://github.com/mbedward/jiffle ?

**Comment by ebocher** [comment]
Other interesting stuffs

https://code.google.com/p/forklabs-jai-operators/

http://www.lac.inpe.br/JIPCookbook/6320-howto-pansharpening.jsp

**Comment by ebocher** [comment]
About MapAlgebra a good alternative could be the BandMathsOp available in BEAM :

https://github.com/bcdev/beam/blob/master/beam-gpf/src/main/java/org/esa/beam/gpf/operators/standard/BandMathsOp.java

**Comment by nicolas-f** [comment]
Do algebra using ScriptEngine api of Java used into JAI operator.

**Comment by ebocher** [comment]
GeoRaster processing is based on JAI API.
