### ISSUE TITLE
GeoRaster driver API

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#579]
An API must be proposed on top of  https://github.com/jai-imageio/jai-imageio-core to read and write WorldFile, GeoTIFF and import and export Esri ASCII.

**Comment by ebocher** [comment]
Note this API will be extended in the future thanks to https://github.com/dragon66/icafe

**Comment by nicolas-f** [comment]
Transfer of raster from PostGIS to H2GIS using Table Link:

```sql
  -- Create link to PostGIS. Using hexadecimal representation of WKB Rasters
  CREATE LINKED TABLE MARSEILLE ('org.orbisgis.postgis_jts_osgi.Driver',
 'jdbc:postgresql_h2://localhost:5432/pgtest','USER','PASSWORD','public','(select rid, rast::varchar from marseille)');
 
 -- Copy data in loca table as a Raster type (storage in Lob)
 create table marslocal(id serial, data raster) as select rid, rast::raster rast from marseille;
```

**Comment by nicolas-f** [comment]
Query
SELECT * FROM MARSLOCAL limit 5;

| ID | RAST |
|---|---------------------------------------------------------------------------------------------------------------|
| 1 | w:38 h:95 bands:3 srid:4326 x:687747 y:4,80709e+06 scalex:2,50000 scaley:-2,50000 skewx:0,00000 skewy:0,00000 |
| 2 | w:38 h:95 bands:3 srid:4326 x:687842 y:4,80709e+06 scalex:2,50000 scaley:-2,50000 skewx:0,00000 skewy:0,00000 |
| 3 | w:38 h:95 bands:3 srid:4326 x:687937 y:4,80709e+06 scalex:2,50000 scaley:-2,50000 skewx:0,00000 skewy:0,00000 |
| 4 | w:38 h:95 bands:3 srid:4326 x:688032 y:4,80709e+06 scalex:2,50000 scaley:-2,50000 skewx:0,00000 skewy:0,00000 |
| 5 | w:38 h:95 bands:3 srid:4326 x:688127 y:4,80709e+06 scalex:2,50000 scaley:-2,50000 skewx:0,00000 skewy:0,00000 |

**Comment by ebocher** [comment]
Don't understand why you put  this example here ?

**Comment by nicolas-f** [comment]
I have created a separated issue

**Comment by ebocher** [comment]
Thanks
