### ISSUE TITLE
Fix the quickstart guide

### ISSUE THREAD

**Issue by boosh** [orbisgis/h2gis#593]
There are errors on `http://www.h2gis.org/docs/dev/quickstart/`

`wget http://tinyurl.com/h2gis-zip -O h2gis.zip` returns some garbled page from jenkins. None of the URLs in it seem to work.

I also can't get the following to work:
```
CREATE ALIAS IF NOT EXISTS SPATIAL_INIT FOR
    "org.h2gis.h2spatialext.CreateSpatialExtension.initSpatialExtension";
CALL SPATIAL_INIT();
```

**Comment by nicolas-f** [comment]
Hi,

Thanks, it has been fixed in the documentation. 

```I also can't get the following to work:```

Do you have an error message ?

**Comment by boosh** [comment]
I think it was a classpath issue. I expect it'd work if I used the standalone jar I was trying to download. I'll close this ticket for now and reopen if I run into any more problems.

Thanks
