### ISSUE TITLE
Raster cache size

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#603]
Use the H2 properties to custom the raster cache size.
```java
 +        private static final int MAX_ROW_CACHE = 32; 
```

**Comment by nicolas-f** [comment]
Fixed in https://github.com/nicolas-f/h2database/commit/37ee69adf6c40a547a7c05d14871394b3b747597

**Comment by ebocher** [comment]
Could you please add an example in the issue.

Thanks a lot

**Comment by nicolas-f** [comment]
The [system property][1] is ```h2.maxRasterRowCache```

You can however specify the row cache when creating the GeoRaster by using GeoRasterRenderedImage#setMaxRowCache(int)

 [1]: https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html

**Comment by ebocher** [comment]
THX
