### ISSUE TITLE
ST_Crop

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#624]
ST_CROP uses the JAI operator.

Crops a raster according the bounding box of the input geometry or set the minX, minY, maxX, maxY of the crop bounds. 

Note :
The crop bounds can not be larger than the actual raster bounds.

Signatures

```sql

ST_CROP(RASTER, GEOMETRY); -> new geoRaster

```

```sql

ST_CROP(RASTER, minX, minY, maxX, maxY); -> new geoRaster

```

**Comment by ebocher** [comment]
I propose to add only one signature : ST_CROP(RASTER, GEOMETRY);
If the user wants to use the second he must create a polygon ?

**Comment by ebocher** [comment]
@gpetit

**Comment by gpetit** [comment]
Ok for me

**Comment by nicolas-f** [comment]
yes or more simply
```sql
select  ST_CROP(the_raster, ST_EXPAND(ST_POINT(1,1), 50,50));
```
