### ISSUE TITLE
Impossible to export SHP under PostGIS

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/h2gis#655]
On saving a table from the geocatalog (right click -> save), OrbisGIS display an error message saying "impossible de créer le ficher".
It appears that in the H2GIS ShapeFile driver, when it reads the WKB in [SHPDriverFunction.java](https://github.com/orbisgis/h2gis/blob/master/h2drivers/src/main/java/org/h2gis/drivers/shp/SHPDriverFunction.java#L107-L109)
```java
byte[] wkb = rs.getBytes(geoFieldIndex);
if (wkb != null) {
    shapeType =  getShapeTypeFromGeometryMetaData(GeometryMetaData.getMetaDataFromWKB(wkb));
}
```
All the byte have impossible values. As example, the very first byte (big endian or little endian) value is `48` instead of `0` or `1`.

PostGIS version : `2.1.2`
PostgreSQL verion : `9.3.10`

**Comment by ebocher** [comment]
Use the ST_AsBinary function to by pass the ewkt format. The 48 corresponds to the SRID code of the geometry.

So in SHPDriverFunction, exportTable method you will have 

```sql
ResultSet rs = st.executeQuery(String.format("select ST_ASBinary(the_geomColumn) , listOfOtherColumns from %s", location.toString()));
```
instead of

```sql
ResultSet rs = st.executeQuery(String.format("select * from %s", location.toString()));
```

or proposes a patch to the JTS reader https://github.com/ebocher/jts.

**Comment by ebocher** [comment]
Documentation
http://postgis.refractions.net/docs/using_postgis_dbmanagement.html#EWKB_EWKT

As EWKB and EWKT are out of the standard. I propose to use ST_AsBinary function.

**Comment by nicolas-f** [comment]
A byte range is 0->255 or -128->128

@ebocher You think that WKB of PostGIS is no longer supported by JTS ?

Do we have to change our driver ?
https://github.com/orbisgis/orbisgis/blob/master/bundles/postgis-jts-osgi/src/main/java/org/orbisgis/postgis_jts_osgi/ResultSetWrapper.java#L970

**Comment by ebocher** [comment]
@SPalominos ?

**Comment by nicolas-f** [comment]
I will do the patch on ResultSetWrapper

**Comment by ebocher** [comment]
ok thanks

**Comment by SPalominos** [comment]
I've tried with putting `ST_AsBinary()` in the SQL request but it isn't really clean.
So a patch on ResultSetWrapper seem to be a better solution.

**Comment by nicolas-f** [comment]
Travis allow us to deploy a PostGIS install, maybe we can add a special unit test by adding a maven PostGIS profile.

**Comment by ebocher** [comment]
It works like a charm.
I will close this ticket. 
I propose to open a new ticket about postgis tests.
Ready ?

**Comment by nicolas-f** [comment]
okay
