### ISSUE TITLE
Push JTS-OSGI to the official JTS lib

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#656]
JTS is available on github. So It would be nice to push on the JTS repo the patch to support osgi.

"A jar with additional information in the jar MANIFEST in order to comply with OSGi environment"

Link : 

https://github.com/dr-jts/jts

**Comment by ebocher** [comment]
@nicolas-f  what do u think ?

**Comment by ebocher** [comment]
@SPalominos to https://github.com/locationtech/jts

**Comment by SPalominos** [comment]
Very good idea! I will give a look to it later.

**Comment by ebocher** [comment]
Done https://github.com/locationtech/jts/pull/62#issuecomment-262055439
But related with the last JTS snapshot
