### ISSUE TITLE
H2GIS Network functions 

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#660]
The SQL network functions must be declared as an OSGI service out of the spatial_ext function.

**Comment by nicolas-f** [comment]
Using H2GIS only the user will have to run an additional sql query in order to register the networks functions

**Comment by ebocher** [comment]
So ?

**Comment by nicolas-f** [comment]
Just to be aware of that.
Something like:

```sql
CREATE ALIAS IF NOT EXISTS SPATIAL_NETWORK_INIT FOR
    "org.h2gis.network.CreateSpatialExtension.initSpatialExtension";
CALL  SPATIAL_NETWORK_INIT();
```

**Comment by ebocher** [comment]
Sounds good for me.

CALL  SPATIAL_NETWORK_EXTENSION();
CALL  RASTER_EXTENSION();
...

**Comment by ebocher** [comment]
Done with the last refactoring.
Network functions are now in the extension module
