### ISSUE TITLE
ST_Intersects takes too long time

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#672]
I'm using the last realease of OrbisGIS.

I'm trying to select buildings from the departement 56 (table "BATI_INDIFFERENCIE") which intersects the agglomeration of Vannes.

So I created a unique polygon that represent my study area (table STUDY).
Then I created spatial indexes on both tables.

Now, I execute the following SQL instruction
```
DROP TABLE IF EXISTS TOTO;
CREATE TABLE TOTO AS SELECT a.* 
    FROM BATI_INDIFFERENCIE a, STUDY b 
WHERE a.THE_GEOM && b.THE_GEOM and ST_INTERSECTS(a.THE_GEOM, b.THE_GEOM);
```

The process is really too long (no result after 5mn).

I tried with or without spatial index on both tables, but the result is the same

@ebocher @nicolas-f

**Comment by nicolas-f** [comment]
Can you post the WKT of STUDY.the_geom ?

**Comment by gpetit** [comment]
[STUDY.zip](https://github.com/orbisgis/h2gis/files/248806/STUDY.zip)

**Comment by nicolas-f** [comment]
You test geometry is composed by 31789 points. That explains the query time.

**Comment by nicolas-f** [comment]
In order to optimize this, I would go for a st_polygonize.

**Comment by gpetit** [comment]
Yes this geometry is complex (even if it's a simple geometry and there is no hole), but this kind of process used to works well in the past.

I'll try ST_Polygonize

**Comment by nicolas-f** [comment]
Sorry I was talking about tessellate

```sql
create table studypol as select * from st_explode('select ST_TESSELLATE(the_geom) the_geom from study');
```

**Comment by nicolas-f** [comment]
then use spatial index on studypol

**Comment by gpetit** [comment]
Thanks @nicolas-f it works. The process takes 47s but I have a result !

**Comment by nicolas-f** [comment]
I'm curious to know how many times PostGIS require to do intersection with a 31789 points geometry and thousands of buildings.

**Comment by gpetit** [comment]
No result with QGis after 10mn (QGis freezed).
... but there is no spatial indexes

**Comment by ebocher** [comment]
Tested on a local postgis server,  this is the same pb

**Comment by gpetit** [comment]
... and same with spatial indexes on QGis --> freeze

**Comment by ebocher** [comment]
Solved ?

**Comment by gpetit** [comment]
Yes we can close
