### ISSUE TITLE
ST_ACCUM

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#674]
from @sbigaret

Description
 No description available.

**Comment by gpetit** [comment]
The function is well documented on the website (see : http://www.h2gis.org/docs/dev/ST_Accum/), but it is not in the SQL Console in OrbisGIS (" No description available.")

I'm not sure, but I believe that we are using the source code to generate the doc in OrbisGIS.
If yes, you can see that the doc in the source code is quite poor :  https://github.com/orbisgis/h2gis/blob/master/h2spatial/src/main/java/org/h2gis/h2spatial/internal/function/spatial/aggregate/ST_Accum.java
