### ISSUE TITLE
Update H2 database from 190 to 192

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#692]
- Change the method getCost to getCostRangeIndex from BaseIndex
More information on https://github.com/h2database/h2database/commit/803988094c5938eb36f579205c6459f2c62c4535

- Update Row, replace by RowFactory
Have look at https://github.com/h2database/h2database/commit/e5b577fa2d5424db101301a165766130de60ccf6

**Comment by ebocher** [comment]
On the pipe https://github.com/ebocher/H2GIS/tree/newH2Release

**Comment by nicolas-f** [comment]
1.4.192 and superior use Java7. We should do the same.

https://github.com/h2database/h2database/issues/300

**Comment by rankinc** [comment]
Apparently, this particular change was accidental. No word yet on if/when it will become official.

**Comment by ebocher** [comment]
Done
