### ISSUE TITLE
Question: plans to switch to a non-copyleft license?

### ISSUE THREAD

**Issue by wikier** [orbisgis/h2gis#701]
I wonder if the project has the discussion of switching to a non-copyleft (Apache, BSD, etc). Thanks in advance.

**Comment by ebocher** [comment]
No.
Could you explain a bit more the LGPL limitation in your case ?

**Comment by wikier** [comment]
I'd like to test it for [MARMOTTA-584](https://issues.apache.org/jira/browse/MARMOTTA-584), but there I'm strictly limited to non-copyleft licenses. That's why I asked.

**Comment by nicolas-f** [comment]
Yes, main software distributed under the apache software license cannot be distributed with lgpl libraries (http://www.apache.org/legal/resolved.html#category-x)

**Comment by wikier** [comment]
Yes, I'm more than aware, that's why I asked for. But it looks there is no plan in the short/mid-term, so never mind. Thanks anyway.
