### ISSUE TITLE
Receive org.cts.crs.CRSException with H2GISFunctions.load

### ISSUE THREAD

**Issue by kytay** [orbisgis/h2gis#711]
Unable to load up v1.3 H2GISFunctions.load or H2GISExtensions.load
Received CRSException when the method is trying to new ST_Transform

Did I miss out anything?

`@Repository
public class H2SpatialUtil {
	
	private static final Logger LOGGER = LoggerFactory.getLogger(H2SpatialUtil.class);
	
	@Autowired
	private DataSource dataSource;
	
	@PostConstruct
	public void load() {
		try {
			H2GISFunctions.load(dataSource.getConnection());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			LOGGER.error("Error found, why? {}", e);
		}
	}
}`

> Caused by: java.lang.NoClassDefFoundError: org/cts/crs/CRSException
> 	at org.h2gis.functions.factory.H2GISFunctions.getBuiltInsFunctions(H2GISFunctions.java:240)
> 	at org.h2gis.functions.factory.H2GISFunctions.registerH2GISFunctions(H2GISFunctions.java:643)
> 	at org.h2gis.functions.factory.H2GISFunctions.load(H2GISFunctions.java:458)
> 	at com.test.h2gis.tutorial.tut01.H2SpatialUtil.load(H2SpatialUtil.java:23)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
> 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:310)
> 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
> 	... 14 more
> Caused by: java.lang.ClassNotFoundException: org.cts.crs.CRSException
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 25 more
>

**Comment by nicolas-f** [comment]
Hi,

Yes, should be a missing jar file.

What Jar files have you included in your project ?

**Comment by kytay** [comment]
`<dependency>
  		<groupId>org.springframework</groupId>
  		<artifactId>spring-context</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>org.orbisgis</groupId>
  		<artifactId>h2gis-ext</artifactId>
  		<version>1.3.0</version>
  	</dependency>
  	<dependency>
  		<groupId>org.springframework</groupId>
  		<artifactId>spring-jdbc</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>org.slf4j</groupId>
  		<artifactId>slf4j-api</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>ch.qos.logback</groupId>
  		<artifactId>logback-classic</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>com.h2database</groupId>
  		<artifactId>h2</artifactId>
  		<version>1.4.192</version>
  	</dependency>
  	<dependency>
  		<groupId>org.springframework</groupId>
  		<artifactId>spring-test</artifactId>
  		<scope>test</scope>
  	</dependency>
  	<dependency>
  		<groupId>junit</groupId>
  		<artifactId>junit</artifactId>
  		<version>4.12</version>
  	</dependency>
  	<dependency>
  		<groupId>org.orbisgis</groupId>
  		<artifactId>cts</artifactId>
  		<version>1.4.0</version>
  	</dependency>`

Above are the dependencies. Tried to add cts.1.4.0.jar as dependency after seeing your reply. But the same error is still appearing,

**Comment by nicolas-f** [comment]
Maybe an issue with your framework not loading declared jars. 

Here a sample that load H2GIS 1.3

https://github.com/orbisgis/orbisgis-samples/tree/master/demoh2gis

You can try running it
```mvn install exec:exec```

**Comment by kytay** [comment]
Thanks.  I have identified the cause to be a currupted cts.jar in my local repository. I have delete the corrupted jar from the repository and update the maven project again. It works now.
