### ISSUE TITLE
ST_NumPoints gives no result

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#718]
I'm using the daily snapshot of OrbisGIS V5.1.

It seems that there is a problem with the ST_NumPoints function.
Examples listed in the doc (http://www.h2gis.org/docs/dev/ST_NumPoints/) don't work.

This is the same with this kind of query
```
UPDATE toto SET Num_point = ST_NUMPOINTS(the_geom) WHERE Evol<0;
```

In any cases, I obtain
```
Execute request 1/1: SELECT ST_NumPoints('MULTIPOINT(2 2, 4 4)')

NULL(NULL)                     
NULL      
```

@ebocher @nicolas-f

**Comment by ebocher** [comment]
ST_NumPoints has been updated few months ago to be conform with OGC and SQL MM specifications.
ST_NumPoints ->  Return the number of points in an ST_LineString
If you want to return the number of points in another geometry you must use ST_NPoints.

The documentation must be updated for the next  H2GIS version that will be synchronized with H2 1.4.193

**Comment by gpetit** [comment]
Ok, my bad ;-)
I'll update the doc asap

**Comment by ebocher** [comment]
No pb. There are many changes in the doc.
