### ISSUE TITLE
Can not create index with linked shp

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#720]
I'm using the V5.1 snapshot (2016/11/02)

When I create an alphanumeric index on a field from a linked shape file, I have this error message
```
Execute request 1/1: CREATE INDEX ON PUBLIC.BATI_INDUSTRIEL(PK)
Feature not supported: "VIEW"; SQL statement:
CREATE INDEX ON public.BATI_INDUSTRIEL(PK) [50100-192]
```
The spatial index works well and no problem wiht imported shape file.

@nicolas-f @ebocher @SPalominos

**Comment by ebocher** [comment]
@nicolas-f 
Is this issue a normal behaviour ?

**Comment by nicolas-f** [comment]
Only spatial index are supported on linked shape file.

https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/H2Table.java#L102

**Comment by nicolas-f** [comment]
I could not use h2 index because this is not compatible with my implementation. (it expect regular h2 table)

**Comment by nicolas-f** [comment]
However PK is the system primary key. So it is useless to add an index on it.

**Comment by gpetit** [comment]
@nicolas-f here PK was just an example. you can rename by "toto" if you prefer ;-)

Consider this is a numeric field on which I want to create an index, because I want use it to join with another table.

And of course I know it's useless to create an index on a primary key

**Comment by ebocher** [comment]
Is it possible to fix this issue in the future?

**Comment by nicolas-f** [comment]
Some days/weeks of work to create an index from scratch or make a pr to change h2 structure.
