### ISSUE TITLE
Maven artifact unusable

### ISSUE THREAD

**Issue by remipassmoilesel** [orbisgis/h2gis#739]
Hi !
Thanks for H2Gis and thanks to share it freely !

I tried to use H2 GIS with Maven but despite several trials I can't make it work. And unfortunately I can not use your packaged distribution of database because I use an internal H2 engine from another project.

I tried to insert this dependency in my POM:
```
       <dependency>
            <groupId>org.orbisgis</groupId>
            <artifactId>h2gis</artifactId>
            <version>1.3.0</version>
        </dependency>
```

But when I execute Maven:
```
[ERROR] Failed to execute goal on project .......: 
Could not resolve dependencies for project ...... 
Failure to find org.orbisgis:h2gis:jar:1.3.0 in .....
```
I tried with 1.2.4 version too, no more results. I tried to delete my Maven local repo, tweak distant repositories, etc ... No more results. 

I tried to clone and install your Github repo but although the local installation ("mvn install") work without error I get the same error message when I want to use it (with version 1.3.1-SNAPSHOT)

I run OpenJDK 1.8 and Maven 3.3.9.

Thanks for your help.

**Comment by SPalominos** [comment]
Hi,
It seems you need to create a spatialised H2 database or to make spatial an existing one.
In both case you will need to use the ```h2gis-functions``` module of H2GIS as Maven dependency and not ```h2gis```.
 - If you have an existing H2 database and you want to make it spatial through H2GIS, you need to call 

[```org.h2gis.functions.factory.H2GISFunctions.load(your connection object here)```](https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java#L459)
 which will register the GEOMETRY type and the SFS functions.
 - If you want a brand new H2/H2GIS database, you need to call [```H2GISDBFactory.createSpatialDataBase(your database name here)```](https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISDBFactory.java#L80)

Hope it would help.

**Comment by remipassmoilesel** [comment]
Great ! Getting started example (http://www.h2gis.org/docs/1.3/quickstart/) worked for me with this configuration:

```
        <dependency>
            <groupId>org.orbisgis</groupId>
            <artifactId>h2gis-functions</artifactId>
            <version>1.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.193</version>
        </dependency>
```
Unfortunately I have to use 1.1.xx version of H2, and it sounds too old for that.

If I can make an observation, from the point of view of a beginner I think it is confusing to have a package named h2gis (which seems to be the main one) that can not be imported in pom.xml

Thanks for your help Sylvain !

**Comment by ebocher** [comment]
Dear @remipassmoilesel 

Thank you for your interest in H2GIS and thank you for the feedback. 
H2GIS is organized in OSGI bundles to take the advantage of modularity. If you run 
```sql
CREATE ALIAS IF NOT EXISTS H2GIS_SPATIAL FOR "org.h2gis.functions.H2GISFunctions.load"
```
you will have the main Simple Feature functions.

with

```sql
CREATE ALIAS IF NOT EXISTS H2GIS_EXTENSION FOR "org.h2gis.ext.H2GISExtension.load";
```
you will be able to use custom H2GIS functions (as network analysis or triangulation)

In few months, new functions will be added to manage and process raster data or run statistical analysis (thanks to Renjin framework). Developers and users can choose that they want.

Feel free if you have any problems or doubts about H2GIS.
