### ISSUE TITLE
H2GIS change module names

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#740]
As noted by @remipassmoilesel it would be nice to improve the readability of the H2GIS project.

We have 
- 8 modules organised under org.h2gis.... 
- ```<groupId>org.orbisgis</groupId>```for the maven group
-``` <artifactId>h2gis-functions</artifactId>``` for the maven artifact
- CREATE ALIAS IF NOT EXISTS H2GIS_EXTENSION FOR "org.h2gis.ext.H2GISExtension.load"; to load only the network functions

I propose the following changes
- 2 modules -> first one named h2gis that contains :h2gis-utilities,h2gis-api, h2gis-test-utilities,h2gis-functions,h2gis-functions-osgi, second one named h2gis-network
- replace org.h2gis by org.orbisgis,
- replace ```<artifactId>h2gis-functions</artifactId> by <artifactId>h2gis</artifactId>```

**Comment by remipassmoilesel** [comment]
It looks great, very simple :+1:

**Comment by SPalominos** [comment]
:+1: , @nicolas-f what do you think about ?

**Comment by nicolas-f** [comment]
My opinion is that it is not necessary to break all packages and dependencies now. Just rename the ``h2gis`` artifact id to ``h2gis-parent``.

**Comment by ebocher** [comment]
The idea is not to break all packages but to merge them. It would be done for the next major release.
I have a preference for a single, an simple approach.

**Comment by ebocher** [comment]
Following my discussions with @nicolas-f , we decide : 

-   rename the h2gis artifact id to h2gis-parent,
-   rename h2gis-functions artifact id to h2gis and  h2gis-functions-osgi
-   remove h2gis-ext and h2gis-ext-osgi 
-   update all the documentation and explain how to load the h2gis-network

**Comment by nicolas-f** [comment]
And add h2gis-network-osgi

**Comment by ebocher** [comment]
Ok drivers must be loaded in h2gis-functions-osgi
