### ISSUE TITLE
Update Quickstart documentation page

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#741]
In the Quickstart documentation page (http://www.h2gis.org/docs/dev/quickstart/), we have to replace the following instruction

```
CREATE ALIAS IF NOT EXISTS H2GIS_SPATIAL FOR "org.h2gis.functions.H2GISFunctions.load";
CALL H2GIS_SPATIAL()
```
by
```
CREATE ALIAS IF NOT EXISTS H2GIS_SPATIAL FOR "org.h2gis.functions.factory.H2GISFunctions.load";
CALL H2GIS_SPATIAL()
```
in order to add "factory"

**Comment by gpetit** [comment]
I made some other small modifications, from my laptop (see #748). But the problem is the same. Jekyll failed to build the page.

**Comment by nicolas-f** [comment]
A fail log in Jekyll build  should be transferred by mail.

**Comment by SPalominos** [comment]
Yes, but the mail doesn't give any error : 
`
The page build failed with the following error:

Page build failed. For more ...
`

I'll contact the support next.
