### ISSUE TITLE
FILE_TABLE from shp file has incorect SRID

### ISSUE THREAD

**Issue by lukaszm89** [orbisgis/h2gis#744]
There is a problem with importing shp files with option FILE_TABLE. I know that this is not importing data directly to database but it is more like linking them.
When data are access the prj file is not read and SRID is not set for the geometry. Method ST_SRID returns always 0. If this is correct behavior it should be at least mentioned in FILE_TABLE function description. 
When importing data via SHPRead function prj file is read and SRID is filed correctly. So there is a significant difference.

**Comment by ebocher** [comment]
Thanks for report
Could you please share a test case or a small dataset to build a test case ?

**Comment by nicolas-f** [comment]
In our unit test here:
https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/test/java/org/h2gis/functions/io/shp/SHPImportExportTest.java#L302

We should check for the expected SRID found in prj file.

**Comment by lukaszm89** [comment]
In unit tests in SHPImportExportTest.java there are only SHPRead calls and they are fine. The problem is when your read shp file with FILE_TABLE function.

**Comment by ebocher** [comment]
Fixed
