### ISSUE TITLE
TCA format data.

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis#750]
Not OGC, but Cadnaa software is able to read this format, and this format is used in CEREMA.

https://docs.typo3.org/typo3cms/extensions/geopicker/Developers/TCA/Index.html

**Comment by ebocher** [comment]
This is not a file format. Where is the specification ? 
Is this format only closed to typo3 CMS ?

**Comment by nicolas-f** [comment]
I will request more information to CEREMA users.

**Comment by nicolas-f** [comment]
Not an issue. It was a text format like csv. Sorry
