### ISSUE TITLE
Support parameters for DriverFunction

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#753]
It will be nice to offer a possibility to send custom parameters related to the driverFunction.

Examples : 

A CSVDriverFunction could be customized with a charset, a separator...
A SHPDriverFunction could be customized with a charset

We could imagine 

to adapt each constructors : 

```java
CSVDriverFunction driver = new CSVDriverFunction(charset, separator);
SHPDriverFunction driver = new SHPDriverFunction(charset)
```

to change the method export and import table 

```java
public void exportTable(Connection connection, String tableReference, File fileName, ProgressVisitor progress)
```

to
```java
public void exportTable(Connection connection,   Map<String, Object> params , ProgressVisitor progress)
where 
Map<String, Serializable> params = new HashMap<String, Object>();
        params.put("fileName", new File("/tmp"));
        params.put("tableReference", "mytable");
       params.put("charset", "utf-8");
```

@SPalominos  @nicolas-f

**Comment by ebocher** [comment]
This
public void exportTable(Map<String, Object> params )
will be better

**Comment by ebocher** [comment]
@nicolas-f any input ?

**Comment by nicolas-f** [comment]
The driver should provide the expected parameters with default values.

```java
interface Parameter {
 String getIdentifier();
 Class getType();
 Object getValue();
 void setValue(Object value) throws IllegalArgumentException; /
 boolean isNotNull(); // for mandatory parameters without default value
}
```

So in the driver instance
```java
List<Parameter> getDefaultImportParameters( ) ;
List<Parameter> getDefaultExportParameters( ) ;

exportTable(Connection connection,   List<Parameter> parameters, ProgressVisitor)
```

**Comment by ebocher** [comment]
Why not a more simple mechanism ?
I understand  the
List<...> getDefaultImportParameters( ) ;
List<...> getDefaultExportParameters( ) ;
in the driver instance
But I can't see any value about a complex object parameter. 

If a value is required and not set the driver must returns an error

With 
Map<String, Serializable> params = new HashMap<String, Object>();
        params.put("distance", 12));

params value could be cast internally in the driver instance.

**Comment by nicolas-f** [comment]
We have to define a parameter class because some parameters could be bound for ex (min max values) or some parameters may be also enumerate (little endian, big endian, ascii)

The idea is to give the resources in order to automatically generate a GUI.

I forgot to say that such default parameters could require the input file beforehand. (autodetect things like file encoding or column separator char)

```java
List<Parameter>  getDefaultImportParameters( File importFile) ;
List<Parameter> getDefaultExportParameters( TableLocation table ) ;
```

**Comment by ebocher** [comment]
The drivers are not use any-more to build automatic GUI. They are used in WPS scripts.

**Comment by ebocher** [comment]
I propose to talk about this issue in a face to face meeting. I don't know if my proposal is interesting.
