### ISSUE TITLE
Update JTS reference in the Wiki

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#754]
In the wiki page https://github.com/orbisgis/h2gis/wiki/1.-Spatial-data we are mentionning JTS. The link provided is not working anymore since the http://tsusiatsoftware.net/ seems to be now a fake commercial website.

In the same spirit, Java Topology Suite is not existing anymore. Since few years, we have to talk about "JTS Topolgy Suite".

IMO we should replace the link by this one : https://sourceforge.net/projects/jts-topo-suite/

@ebocher @nicolas-f

**Comment by ebocher** [comment]
JTS is now hosted by LocationTech https://www.locationtech.org/projects/technology.jts

**Comment by ebocher** [comment]
Done
