### ISSUE TITLE
Extend doc for OSMRead, GPXRead and ST_Graph

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#765]
The H2GIS DOC must be extended because the 3 functions  OSMRead, GPXRead and ST_Graph support now a boolean option to delete the existing tables (based on a prefix).

**Comment by ebocher** [comment]
add also a doc on ST_RemoveRepeatedPoint with tolerance

**Comment by ebocher** [comment]
improve ST_Expand doc

**Comment by gpetit** [comment]
@ebocher concerning ST_Expand, if you are talking about https://github.com/orbisgis/h2gis/commit/4178b782b33993349cd257daeb77168fbf07a479, the doc was already ok. X and Y were mentionned

**Comment by gpetit** [comment]
Done @ebocher you can close this issue
