### ISSUE TITLE
PostGIS: St_Collect St_Accum

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis#766]
There is an issue on function compatibility between PostGIS and H2GIS.

On H2GIS the function ST_Accum has the same behaviour than ST_Collect of PostGIS.

On PostGIS  ST_Accum return an array of geometry object.

http://postgis.net/docs/ST_Accum.html
http://postgis.net/docs/ST_Collect.html

**Comment by ebocher** [comment]
I can do that but this change will break some scripts...
So It will be done with a new H2GIS version ?

**Comment by nicolas-f** [comment]
I do not say we should change ST_Accum.

Maybe we can just add an alias st_collect.

**Comment by ebocher** [comment]
But why not change the ST_Accum to return an array of geometries and align H2GIS on PostGIS ?

**Comment by ebocher** [comment]
Done
