### ISSUE TITLE
H2GIS select version function

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#768]
Add a function to return the H2GIS version

SELECT H2GIS_Version()

@nicolas-f  and @gpetit

**Comment by ebocher** [comment]
It would be nice to return the version  at runtime using

getClass().getPackage().getImplementationVersion()

This approach needs som change in the H2GIS pom's
http://blog.soebes.de/blog/2014/01/02/version-information-into-your-appas-with-maven/

**Comment by nicolas-f** [comment]
The Bundle-Version can be extracted from the h2gis manifest at runtime

**Comment by ebocher** [comment]
Yes but we must parse the manifest file?
With 
getClass().getPackage().getImplementationVersion()
the metadata is set in the classloader

**Comment by nicolas-f** [comment]
I don't think that getImplementationVersion is equivalent to Bundle-Version.

There is a method to read this attribute (already done by OrbisGIS by the way)

http://stackoverflow.com/questions/1272648/reading-my-own-jars-manifest

**Comment by ebocher** [comment]
@gpetit 
This function must be also documented.

**Comment by gpetit** [comment]
I'm on it

**Comment by gpetit** [comment]
Where is the code ? Not sure this function has been merged ?

**Comment by ebocher** [comment]
https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/system/H2GISversion.java

**Comment by ebocher** [comment]
And the test
https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/test/java/org/h2gis/functions/system/SystemFunctionTest.java#L134

**Comment by gpetit** [comment]
This function has been documented : see #783
