### ISSUE TITLE
Release H2GIS steps

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#776]
Step 1 
After the PR #775 and #774 we must release H2GIS.

Step 2
Update H2 database from 1.4.193 to 1.4.194.

Step 3
Release CTS
Update CTS in H2GIS 

@gpetit

**Comment by ebocher** [comment]
Update also
The http://www.h2gis.org/docs/home/ 
And set news page

**Comment by ebocher** [comment]
@SPalominos could please
-  push on maven the last 1.3.1 of H2GIS.
There is a doc here https://github.com/orbisgis/h2gis/wiki/Release-H2GIS-into-maven-central

- create a new release on github and copy paste the change log available here https://github.com/orbisgis/h2gis/pull/781

Thanks a lot

**Comment by SPalominos** [comment]
I will do it as soon as possible.

**Comment by ebocher** [comment]
@SPalominos  to push H2GIS 1.3.1 you must used  https://github.com/orbisgis/h2gis/releases/tag/v1.3.1

and run theses commands

mvn release:clean
mvn release:perform -Dtag=v1.3.1 -P standalone -DconnectionUrl=scm:git:https://github.com/orbisgis/h2gis.git

Note it doesn't work on my laptop it seems related to my GPG KEY.

**Comment by ebocher** [comment]
Step 1 and 2 done

**Comment by gpetit** [comment]
What abou step 3. Hope it's done since the v1.3.1 has been released ;-)

**Comment by SPalominos** [comment]
Yes it's done, I haven't updated the issue.
