### ISSUE TITLE
H2GIS with Python

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#779]
Add a wiki page to explain how to use H2GIS with Python.
@gpetit could talk with @nicolas-f about that ?
A very good doc is available here https://github.com/Ifsttar/NoiseModelling/wiki/11-Scripting-with-Python

**Comment by gpetit** [comment]
@nicolas-f how can I help you to create this wiki page.
Reading the NoiseModelling page I can understand the main ideas ... but maybe I will need your help to me clear and right

**Comment by nicolas-f** [comment]
The tutorial will not be the same. The beginning is to follow the quick start http://www.h2gis.org/docs/1.3.2/quickstart/

**Comment by gpetit** [comment]
Hum ok ... let's start to built the skeleton of this page ... and then try to fill the doc : https://github.com/orbisgis/h2gis/wiki/4.4-Use-H2GIS-with-Python
