### ISSUE TITLE
Add doc for ST_MakeValid

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#782]
We have to create the documentation for the function ST_MakeValid (see #777 ).

I just pushed a pre-version of the doc file here #783 (will be updated / not to merge right now)

Here I have some questions for @mukoki

- Parameter: ```preserveCoordDim``` : in the doc, we say :"if true, then "Preserves third and fourth ordinates" and if false "Preserves third ordinates but not fourth one"
So if i'm not wrong, in both cases, third ordinates will be preserved. So this parameter is only here for fourth ordinates ?

- Parameter: ```preserveGeomDim``` : I'm afraid I can not find examples to illustrate this parameter. I tried but in all cases (1rst signature / 2nd signature (with true or false)) the result is always the same. Maybe I'm missing something ?!

@ebocher

**Comment by mukoki** [comment]
Hi


Le 24/03/2017 à 16:52, Gwendall Petit a écrit :
>
> We have to create the documentation for the function ST_MakeValid (see 
> #777 <https://github.com/orbisgis/h2gis/issues/777> ).
>
> I just pushed a pre-version of the doc file here (will be updated / 
> not to merge right now)
>
> Here I have some questions for @mukoki <https://github.com/mukoki>
>
>  *
>
>     Parameter: |preserveCoordDim| : in the doc, we say :"if true, then
>     "Preserves third and fourth ordinates" and if false "Preserves
>     third ordinates but not fourth one"
>     So if i'm not wrong, in both cases, third ordinates will be
>     preserved. So this parameter is only here for fourth ordinates ?
>
Yes, JTS use CoordinateSequence to store coordinates information in 2D, 
3D or 4D. But many operations use the Coordinate structure which just 
has a x, y and z.
Preserving the z is "natural" in JTS, but preserving a 4th dimension 
needs a special effort to retrieve the 4th ordinate after any operation 
implying the use of Coordinate.

Note : MakeValidOp may add new points to node the original set of lines 
(especially to make polygons valid). New points have just a x and a y. 
No interpolation is performed if original geometry is 3D or 4D.

>  *
>
>
>  *
>
>     Parameter: |preserveGeomDim| : I'm afraid I can not find examples
>     to illustrate this parameter. I tried but in all cases (1rst
>     signature / 2nd signature (with true or false)) the result is
>     always the same. Maybe I'm missing something ?!
>
If you try with the geometry LINESTRING(1 1, 1 1) which is an invalid 
LINESTRING (null length)
preserveGeomDim = true should produce LINESTRING EMPTY
preserveGeomDim = false should produce POINT(1 1)

The second option preserves the coordinate, while the first preserve the 
dimension of the geometry.

Regards,

Michaël

**Comment by gpetit** [comment]
Sorry for the delay

Thanks @mukoki for your answer. I will check and update the doc

**Comment by gpetit** [comment]
Doc is now on-line : http://www.h2gis.org/docs/dev/ST_MakeValid/
Thanks @mukoki
