### ISSUE TITLE
Update h2gis.org

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#797]
Change dev to the 1.3.2-Snapshot version
Copy and create a new entry 1.3.1 ( last release)
Add news entry H2GIS 1.3.1 Released based on https://github.com/orbisgis/h2gis/releases/tag/v1.3.1 change log
and Let's Tweet Again

**Comment by gpetit** [comment]
Tweet done : https://twitter.com/H2GIS/status/854690059152437248

@ebocher I think you can close this issue
