### ISSUE TITLE
LGPL including GPL dependency

### ISSUE THREAD

**Issue by StephaneWasserhardt** [orbisgis/h2gis#802]
H2GIS is licenced under LGPL3 but [https://github.com/orbisgis/h2gis/blob/master/h2gis-dist/pom.xml](h2-dist) includes a dependency to postgis-jts-osgi which is GPL.

**Comment by ebocher** [comment]
Thanks postgis-jts-osgi must be in LPGL.

**Comment by gpetit** [comment]
Dear @StephaneWasserhardt thanks for your warning.
The licence has been changed. So you are invited to check and close this issue if it's ok for you.

**Comment by StephaneWasserhardt** [comment]
It's perfect. Thank you for the quick fix !
