### ISSUE TITLE
Invalid cost of PK Index

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis#806]
Pk Index of linked table return a superior cost than spatial index.

Have to write this unit test with a linked table (spatial indexed)

```java
 private void testLinkedShpSpatialIndexFlatQuery() throws SQLException {
        Connection conn = getConnection(URL);
        Statement stat = conn.createStatement();
        // TODO Add linked shape file BUILDINGS
        stat.execute("CREATE SPATIAL INDEX ON PUBLIC.BUILDINGS(THE_GEOM);\n");
        try (ResultSet rs = stat.executeQuery("EXPLAIN SELECT * FROM " +
                "BUILDINGS ORDER BY PK LIMIT 51;")) {
            assertTrue(rs.next());
            assertTrue(rs.getString(1).contains("PRIMARY_KEY"));
        }
    }
```

This fix may be done here:

https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/H2TableIndex.java#L163

**Comment by ebocher** [comment]
I'm not able to fix this issue before 2 or 3 weeks so any help is welcome ;-)

**Comment by ebocher** [comment]
@nicolas-f 
Do you have some time to fix this issue ?

**Comment by nicolas-f** [comment]
Not today, but if I have a remainder next week..
