### ISSUE TITLE
Issue with ST_SetSrid ST_Transform and linked shape file

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis#807]
Using the following linked shape file
[Nantes Centre.zip](https://github.com/orbisgis/h2gis/files/942701/Nantes.Centre.zip)

and executing the following query

```sql
drop table if exists roads_2154;
create table roads_2154 as select st_transform(st_setsrid(the_geom, 4326), 2154) the_geom, OSM_ID, CODE, FCLASS, NAME, REF, ONEWAY, MAXSPEED, LAYER, BRIDGE, TUNNEL from roads;
select st_extent(the_geom) from roads_2154;
```

The result has not been transformed and show an extent in the epsg 4326. But the funtion ST_SRID return 2154

**Comment by nicolas-f** [comment]
When using import (copy), the projection is done.

**Comment by gpetit** [comment]
And the same if the roads.shp has a 4326 .prj file

"_When using import (copy), the projection is done._" : sometimes there is some few errors (e.g 20 lines not reprojected).

**Comment by nicolas-f** [comment]
Sorry, this week, I don't have the time to work on this issue.

**Comment by gpetit** [comment]
Note that with an imported layer, the behaviour is strange: 

1. import the layer and execute the sql instructions
2. the number of well reprojected lines is variable (between 50 and 99%)
3. just re-execute the script : 100% of lines are well reprojected

**Comment by ebocher** [comment]
I'm not able to fix this issue before 2 or 3 weeks so any help is welcome ;-)

**Comment by ebocher** [comment]
Any help are welcome

**Comment by gpbp** [comment]
Can I do it?

**Comment by ebocher** [comment]
is geojson  implemented ?
If yes you can try to fix this issue.

**Comment by gpbp** [comment]
yeah, now I'm trying to make our drivers support null object. 
I'll see if I can do with this issue.

**Comment by gpetit** [comment]
This issue is linked with https://github.com/orbisgis/orbisgis/issues/988

SET CACHE_SIZE 0 should resolve the problem

**Comment by gpetit** [comment]
Since #988 is closed, this issue should be resolved, but I made a last test and I still have some problems.
* I imported the road.shp
* I executed the instructions
* I load the ROADS_2154 table into the TOC --> nothing in the map (even if I zoom on the layer)
* I rexecute the instruction (the table is still in the TOC) --> refresh the TOC and the map --> nothing
* I remove the table from the TOC and load it once again (in the TOC) --> ok, the layer is displayed in L93
