### ISSUE TITLE
Illogical alternatives found in class GeoJsonReadDriver

### ISSUE THREAD

**Issue by gpbp** [orbisgis/h2gis#811]
I found something weird when I read the class last week which I think logically incorrect. (line 517, method parsePolygonMetadata)

![screenshot from 2017-05-02 10-43-18](https://cloud.githubusercontent.com/assets/18648177/25610604/2bbc5e32-2f24-11e7-9be8-f492fbd72b36.png)

Will we do the same thing when linesIndex == 0 and linesIndex != 0?

Same thing happens if you guys roll into line 525

![screenshot from 2017-05-02 10-45-47](https://cloud.githubusercontent.com/assets/18648177/25610692/854b787a-2f24-11e7-8573-7d3f9dbf3505.png)

Can we just remove the alternatives and write directly parseCoordinateData and jp.nextToken? Or the machine would react in the different way if we changed it?

**Comment by ebocher** [comment]
Good catch if the code do the same please remove it.
Don't forget to send one PR by  fixed issue

**Comment by ebocher** [comment]
Do not

**Comment by ebocher** [comment]
This issue must be closed when the PR is submitted .
