### ISSUE TITLE
Issue while testing GeoJsonReadDriver class (Error: malformed GeoJson file)

### ISSUE THREAD

**Issue by gpbp** [orbisgis/h2gis#812]
I was trying to call GeoJsonRead with a geojson file found on noise-planet.org(France.zip/France_Alsace_Bas-Rhin.areas.geojson). Then this happened.

![screenshot from 2017-05-02 15-34-15](https://cloud.githubusercontent.com/assets/18648177/25619943/f0b3fb8c-2f4c-11e7-9247-bd0a647f1bb2.png)

After many tests, I'm pretty sure it occured anytime the program called parsePropertiesMetadata() (line 671). That's why I added another line to the code (System.out.println("property:" + jp.getText())) to see the output.

![screenshot from 2017-05-02 15-40-20](https://cloud.githubusercontent.com/assets/18648177/25620133/ac496350-2f4d-11e7-9854-10d39993778c.png)

Then I realized that the program missed a lot of tokens when it parsed the geojson file.
This is the output:
![screenshot from 2017-05-02 15-49-03](https://cloud.githubusercontent.com/assets/18648177/25620503/f077d146-2f4e-11e7-8c83-7ce12559f9b0.png)

As you can see above, after "1484846967000", it begins with "[" and "47" which is not what I expected when I read "France_Alsace_Bas-Rhin.areas.geojson" (line 4, token "leq_profile"). I expected "[" and "48".

**Comment by ebocher** [comment]
This is a bug in the parser that must be fixed.

**Comment by SPalominos** [comment]
Yes, it seems that the parser reads one value out of two. It should read the whole array as value.
@gpbp As you are working on geojson parsing, I assign you to this issue.
(Tips, instead of screenshots, you can also use [markdown](https://guides.github.com/features/mastering-markdown/) to quote code with syntax coloration)

**Comment by gpbp** [comment]
@SPalominos Ok, I'll try to do it next time.
Thanks you guys.

**Comment by ebocher** [comment]
Is this issue fixed ?

**Comment by gpbp** [comment]
yes, I fixed it
