### ISSUE TITLE
Q&A: about metadata methods in GeoJsonReaderDriver class

### ISSUE THREAD

**Issue by gpbp** [orbisgis/h2gis#815]
I just realized that methods with the "metadata" term behind (Ex: parsePropertiesMetadata) just "parse" the geojson file. It doesn't have to store the data or something? And how do we store it exactly?

(ps: I still don't have permission to label my issues. I really want to have a question label on this but I can't)

**Comment by ebocher** [comment]
parsePropertiesMetadata is used to collect information in order to create the table that will store the geojson.
