### ISSUE TITLE
Difficulty while parsing and writing JSON Object

### ISSUE THREAD

**Issue by gpbp** [orbisgis/h2gis#819]
What should I do when the Json file contains something like this: "member": {"member1": value1, "member2": value2} in "properties" member. Should I put all into an String object and set up VARCHAR as the type of this column?

**Comment by ebocher** [comment]
Please post a more concrete example relate with the geojson specification

**Comment by gpbp** [comment]
I don't have any example, just something I imagine. This is the only solution I figured out, otherwise it would be a dead end.

**Comment by ebocher** [comment]
@nicolas-f 
What about if the store the json collection in blob data type ?

**Comment by nicolas-f** [comment]
You can not store hierarchical objects in a single table. If you really want to support this feature you need to create multiple tables.

**Comment by SPalominos** [comment]
Ok, thanks @nicolas-f
So for now @gpbp will let this case empty an it will be implemented later.

**Comment by ebocher** [comment]
Seems fixed with the last PR ?
