### ISSUE TITLE
Which standard to write?

### ISSUE THREAD

**Issue by gpbp** [orbisgis/h2gis#820]
In which standards we will write our GeoJson files? I mean the GeoJsonWriterDriver class has to write a GeoJson file from a spatial table but I don't know if I should keep old methods that are only used by the 2008 spec.

**Comment by ebocher** [comment]
You must write the Geojson file to the last specification.
@SPalominos  what do you think ?

**Comment by SPalominos** [comment]
I agree, by default we should use the very last version.
