### ISSUE TITLE
About linear rings: counterclockwise recognition.

### ISSUE THREAD

**Issue by gpbp** [orbisgis/h2gis#823]
Are there any functions that help us to recognize a counterclockwise linear ring and identify the exterior ring when it comes to Polygon with holes.

**Comment by ebocher** [comment]
What exactly do you want to do ?

In the JTS library the order of the coordinates is closed to http://www.opengeospatial.org/standards/sfa

If I'm not wrong :  
Simple Features Access specifies a counter-clockwise direction for outer rings as of version 1.2.1 document

You must check the JTS api.

**Comment by gpbp** [comment]
Because rfc 7946 only accepts Polygons with counterclockwise exterior ring and clockwise holes.

I'll check the JTS api.

**Comment by gpbp** [comment]
the order of the coordinates in the JTS library is exactly the same as rfc 7946. So when I stock information into a spatial table, coordinates will follow directly the right-hand rule?

**Comment by ebocher** [comment]
The H2GIS uses JTS and PostGIS the GEOS lib closed to JTS, in conclusion the coordinate order will be the same rfc 7946

**Comment by gpbp** [comment]
That's great, we don't have to change anything. I'll close this issue.
