### ISSUE TITLE
Kernel density estimation 

### ISSUE THREAD

**Issue by pierromond** [orbisgis/h2gis#828]
Does it exist any easy implementation or tutorial for kernel density estimation with H2GIS ? as presented in http://lara.inist.fr/bitstream/handle/2332/879/0949_T1.pdf;jsessionid=338AEBFCD7E542E25D810933CED1790C?sequence=4 for example.

**Comment by ebocher** [comment]
Renjin with H2GIS will be a good option.
You can test https://stat.ethz.ch/R-manual/R-devel/library/stats/html/density.html in OrbisGIS RConsole
https://github.com/orbisgis/orbisgis-official-plugins/tree/master/r-console

**Comment by pierromond** [comment]
Good idea, it will be the opportunity to test Renjin. Thank you.
