### ISSUE TITLE
Improve SHPRead function ?

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#839]
It would be nice if the SHPRead function returns a ValueResulSet as CSVRead function. So the user will be able to do something like

SELECT SUM(ST_AREA(THE_GEOM)) AS total from  (SELECT * FROM SHPREAD('/tmp/myFile.shp')) GROUP BY CODE_INSEE;

It is  closer to the SQL syntax than "CALL SHPRead".

**Comment by nicolas-f** [comment]
SHPREAD must create a primary key column. This thing is not possible with table result set.

**Comment by ebocher** [comment]
So you think that we cannot emulate a SERIAL column with a SimpleResultSet ?

**Comment by nicolas-f** [comment]
SERIAL is not a column type its an alias for auto increment primary key when creating tables.

**Comment by ebocher** [comment]
Ok. According to you it's not possible to do that ?

**Comment by nicolas-f** [comment]
It should be another function name.

**Comment by ebocher** [comment]
Maybe : 

SHPREAD -> Read a file
SHPImport -> Import a file (previously SHPREAD)

**Comment by ebocher** [comment]
@gpetit

**Comment by gpetit** [comment]
Ok to distinguish the behaviours.
* SHPRead : the shape file is imported as a whole and there is no possibility to make query on it.
* SHPImport : the shape file is imported and we can call it thanks to sub query

In both cases, a PK is added

**Comment by ebocher** [comment]
When the SHP is imported the data are stored in the database so you can do what you want in SQL.

**Comment by gpetit** [comment]
Yes I know but your initial question was to be able to make SQL selection during the import step (not once the shp is stored into a table) ? Isn't it ?

**Comment by ebocher** [comment]
It would be nice to support this syntax for all driver functions

```sql
CALL SHPWRITE('/tmp/theshape.shp', '(SELECT * FROM geomtable where st_area(the_geom) >10000 )';
```

**Comment by ebocher** [comment]
CALL SHPWRITE('/tmp/theshape.shp', '(SELECT * FROM geomtable where st_area(the_geom) >10000 )'[,encoding] );

is now supported

@gpetit

**Comment by ebocher** [comment]
@gpetit ping for doc

**Comment by gpetit** [comment]
The `SHPWRITE` function has been updated (in the code and the doc). 
But what about the `SHPREAD` one ? Are we still planning to update it following @ebocher 's reflexions?

**Comment by ebocher** [comment]
SHPREAD has been updated with the signature : 

```
 addProperty(PROP_REMARKS, "Read a shape file and copy the content in the specified table."+
                "\n SHPRead(..."+
                "\n Supported arguments :" +
                "\n path of the file" +
                "\n path of the file, table name"+
                "\n path of the file, true for delete the table with the same file name"+
                "\n path of the file, table name, true to delete the table name"+
                "\n path of the file, table name, true to delete the table name"+
                "\n path of the file, table name, encoding chartset"+
                "\n path of the file, table name, encoding chartset, true to delete the table name");
```
Note that SHPRead doesn't support zip archive as entry

**Comment by gpetit** [comment]
Ok thanks
