### ISSUE TITLE
Command to load hsgis_spatial cited in readme is wrong

### ISSUE THREAD

**Issue by jtownson** [orbisgis/h2gis#842]
The usage section of the readme gives the classname to load hsgis_spatial as
```CREATE ALIAS IF NOT EXISTS H2GIS_SPATIAL FOR "org.h2gis.functions.H2GISFunctions.load";```

I think the correct alias/classname should be
```CREATE ALIAS IF NOT EXISTS H2GIS_SPATIAL FOR "org.h2gis.functions.factory.H2GISFunctions.load";```

**Comment by nicolas-f** [comment]
Hi,

Thanks for the feedback I will update the readme.

**Comment by ebocher** [comment]
Thanks
