### ISSUE TITLE
Remove usage of java.nio.file

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis#844]
Android does not support java.nio.file package. We have to find a workaround in order to be compatible with Android.

https://github.com/orbisgis/h2gis/search?utf8=%E2%9C%93&q=%22import+java.nio.file%22&type=

**Comment by nicolas-f** [comment]
Related to this thread http://h2gis.1099522.n5.nabble.com/Attach-shapefile-on-Android-td87.html#a99

**Comment by ebocher** [comment]
Seems available  in API level 26  https://developer.android.com/reference/java/nio/file/DirectoryStream.html

**Comment by ebocher** [comment]
Sorry but we don't have the resources to maintain compatibility with Android
