### ISSUE TITLE
Add a page Products and Projects that use H2GIS

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#846]
List all Products and Projects that use H2GIS

ie : Dari/Brightspot https://github.com/perfectsense/dari

**Comment by ebocher** [comment]
https://github.com/iyusuf/micro-map-service

**Comment by ebocher** [comment]
https://www.youtube.com/watch?v=7fMqggQzqTk

**Comment by ebocher** [comment]
https://bitbucket.org/treyerl/luci

**Comment by ebocher** [comment]
http://www.openjump.org/

**Comment by ebocher** [comment]
https://blog.gvsig.org/2018/02/21/gvsig-desktop-2-4-is-already-available/

@gpetit ping

**Comment by ebocher** [comment]
https://issues.apache.org/jira/browse/CALCITE-1968

**Comment by nicolas-f** [comment]
Calcite use only the website content (list of spatial functions) of H2GIS. Not the actual library.

**Comment by gpetit** [comment]
I'm on it

**Comment by gpetit** [comment]
I think we can close this issue. If new tools or projects are detected I will update the "users" page
