### ISSUE TITLE
ST_Graph not found in 1.3.2

### ISSUE THREAD

**Issue by oscar9** [orbisgis/h2gis#850]
If you download h2gis-dist-1.3.2-bin.zip from http://www.h2gis.org/
And execute: java -jar h2gis-dist-1.3.2.jar
CALL ST_GRAPH();

Function "ST_GRAPH" not found; SQL statement:select ST_Graph() [90022-196] 90022/90022 (Ayuda)org.h2.jdbc.JdbcSQLException: Función "ST_GRAPH" no encontradaFunction "ST_GRAPH" not found; SQL statement:select ST_Graph() [90022-196]    at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)    at org.h2.message.DbException.get(DbException.java:179)    at org.h2.message.DbException.get(DbException.java:155)    at org.h2.command.Parser.readJavaFunction(Parser.java:2487)    at org.h2.command.Parser.readFunction(Parser.java:2539)    at org.h2.command.Parser.readTerm(Parser.java:2876)    at org.h2.command.Parser.readFactor(Parser.java:2390)    at org.h2.command.Parser.readSum(Parser.java:2377)    at org.h2.command.Parser.readConcat(Parser.java:2347)    at org.h2.command.Parser.readCondition(Parser.java:2178)    at org.h2.command.Parser.readAnd(Parser.java:2150)    at org.h2.command.Parser.readExpression(Parser.java:2142)    at org.h2.command.Parser.parseSelectSimpleSelectPart(Parser.java:2053)    at org.h2.command.Parser.parseSelectSimple(Parser.java:2085)    at org.h2.command.Parser.parseSelectSub(Parser.java:1940)    at org.h2.command.Parser.parseSelectUnion(Parser.java:1755)    at org.h2.command.Parser.parseSelect(Parser.java:1743)    at org.h2.command.Parser.parsePrepared(Parser.java:449)    at org.h2.command.Parser.parse(Parser.java:321)    at org.h2.command.Parser.parse(Parser.java:293)    at org.h2.command.Parser.prepareCommand(Parser.java:258)    at org.h2.engine.Session.prepareLocal(Session.java:578)    at org.h2.engine.Session.prepareCommand(Session.java:519)    at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)    at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:176)    at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)    at org.h2.server.web.WebApp.getResult(WebApp.java:1380)    at org.h2.server.web.WebApp.query(WebApp.java:1053)    at

**Comment by SPalominos** [comment]
Hi, thank you for reporting this issue.

After running `java -jar h2gis-dist-1.3.2.jar`, did you initialized the H2GIS extension like shown in the [H2GIS quick-start](http://www.h2gis.org/docs/1.3.2/quickstart/) before executing the `CALL ST_GRAPH();` instruction ?

**Comment by oscar9** [comment]
Ok, it's working, my bad. Awesome job, thanks for the reply!

**Comment by SPalominos** [comment]
Great, don't hesitate to post if you encounter another issue.
