### ISSUE TITLE
building shadow

### ISSUE THREAD

**Issue by iamjinlei** [orbisgis/h2gis#866]
I am trying to get a shadow for my polygon by directly calling ST_SunPosition.sunPosition() and ST_GeometryShadow.computeShadow. However, the produced shadow seems wrong. The expected shadow should reside on the north side of the building, but that is not what I saw. Below is my sample code. Poly is a simple rectangle such as [(0,0), (100, 0), (100, 40), (0, 40), (0, 0)].

Point hz = GeometryAlgo.createPoint(120.169, 30.255);
Geometry sunPos = ST_SunPosition.sunPosition(hz);
Geometry shadow = ST_GeometryShadow.computeShadow(poly, sunPos, 4 * Metric.METER);

What did I do wrong here? Please advice. I tried google online but all I get are sql statements.

**Comment by ljinfb** [comment]
I further verified with other online tools. It looks like the sun position calculation is correct. But my shadow become upside down. Am I doing something stupid? Thanks!

**Comment by ebocher** [comment]
```sql
select ST_GEOMETRYSHADOW('POLYGON ((0 0, 100 0, 100 40, 0 40, 0 0))'::GEOMETRY, ST_SUNPOSITION('POINT(120.169 30.255)'::GEOMETRY), 4);
```
returns
POLYGON ((0 40, 2.8956618538979484 40.05901178960749, 102.89566185389795 40.05901178960749, 102.89566185389795 0.0590117896074885, 100 0, 100 0.0590117896074885, 100 40, 2.8956618538979484 40, 0 40))

Note that ST_SunPosition.sunPosition receives also a location and a time.

**Comment by ljinfb** [comment]
@ebocher  thanks for looking into this issue.

Is the coordinate system different from JTS? JTS has negative Y on north and positive Y on south. So your returned polygon shadow also resides on the south side of the building according to JTS.

Here is my Java code:

```
public void test() {
    final SimpleDateFormat parser = new SimpleDateFormat("yyyy-MM-dd HH:mm:ssZ");
    Date date;
    try {
      date = parser.parse("2017-01-20 09:00:00+0800");
    } catch (ParseException e) {
      return;
    }

    Calendar cal = Calendar.getInstance();
    cal.setTime(date);
    Point sunPos = (Point) ST_SunPosition.sunPosition(
        new GeometryFactory().createPoint(new Coordinate(120.169, 30.225)), cal.getTime());

    Polygon polygon = new GeometryFactory().createPolygon(new Coordinate[]{
        new Coordinate(0, 0),
        new Coordinate(100, 0),
        new Coordinate(100, 40),
        new Coordinate(0, 40),
        new Coordinate(0, 0)
    });
    Geometry shadow = ST_GeometryShadow.computeShadow(
        polygon, sunPos.getX(), sunPos.getY(), 4);
}
```

Here is the results:
```
POLYGON ((-7.467652346278686 6.623241910095367, -7.467652346278686 46.623241910095366, 92.53234765372132 46.623241910095366, 100 40, 92.53234765372132 40, 0 40, 0 6.623241910095367, 0 0, -7.467652346278686 6.623241910095367))
```

It is also on the south side of the building. After negating sun position's x/y value, it seems to produce correct shadow (by comparing to other online shadow tool).

```
 Geometry shadow = ST_GeometryShadow.computeShadow(
        -polygon, sunPos.getX(), -sunPos.getY(), 4);
```

**Comment by ebocher** [comment]
Thanks a lot we will look on it.

**Comment by SPalominos** [comment]
Sorry, we don't have an error with your data, the shadow is at the north-west of the building as espected.
