### ISSUE TITLE
ST_Transform is not working as expected 

### ISSUE THREAD

**Issue by willome** [orbisgis/h2gis#873]
```
select ST_AsText(ST_Transform(ST_SetSRID(ST_Point(379550.883, 1815125.223), 4326), 2154)) 
``` 

is not throwing any error, but Postgis does : ERROR: transform: couldn't project point (379551 1.81513e+06 0): latitude or longitude exceeded limits (-14).

This has been tested on 1.3.2 and 1.4.0-SNAPSHOT. I saw some bugs which have been fixed on ST_Transform, but it seems a bug is still present.

**Comment by nicolas-f** [comment]
Hi,

The explanation for the error is that the latitude and longitude of the provided coordinates are outside the bounds defined by the projection used. The WGS84 projection (4326) is bounded from -180° to +180°.

It seems that you have not provided the correct argument projection for the ST_SETSRID function.

```sql
select ST_AsText(ST_Transform(ST_SetSRID(ST_MakePoint(379550.883, 1815125.223), 2154), 4326));

-- POINT (0.6665174699701417 6.38514521272767) 
```

**Comment by willome** [comment]
Well I know that is the wrong projection : the sql example I wrote is erroneous (it was made on purpose) and it just show you that the error is NOT present in H2Gis, but occured as expected with PostGis.

**Comment by ebocher** [comment]
Declared in CTS https://github.com/orbisgis/cts/issues/96
