### ISSUE TITLE
ST_Drape

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#877]
A function to drap a geometry to a geometry that contains a set of triangles

```sql
geometry ST_Drape(  
  geomToDrap geometry,  triangles geometry
)
```
Usage
```sql
SELECT ST_Drape(a.the_geom, st_accum(b.the_geom)) from lines a, triangles b where st_intersects(a.the_geom, b.the_geom)
```

**Comment by gpetit** [comment]
Where does the name "ST_Drape" come from ?
For PostGIS it seems this function is for raster : https://trac.osgeo.org/postgis/ticket/2327 (but this ticket is 5 years old and I don't see another reference on internet)

**Comment by ebocher** [comment]
This function comes from a discussion with @nicolas-f .
The idea is to drape a geometry to a set of triangles in order to interpolate the missing z values in the input geometry.

**Comment by gpetit** [comment]
Ok it will be great. Just two remarks: 
* why "forcing" to use triangles (b.the_geom) ? I understand that the function will use triangles to determine the missing z values but why not saying that the geomB is a generic geometry (e.g points (polutant concentrations) lines (roads),  polygons (buildings)). For me the generation of triangles is something that should be transparent for users.
* can we (or do we have to) give the possibility to specify the resolution of triangles ? Because depending on their sizes, the z values interpolated will be more or less accurate.

**Comment by ebocher** [comment]
Do not understand the first bullet point. But, 
if you want to compute the z value of a point inside a polygon you must have a plane. The triangles are the most easy way to do that. You can divide the polygon as a set of triangles.

Considering the second bullet, triangles are the input mesh data to drape the geometry (first argument) so the user must adapt the triangulation before.

**Comment by gpetit** [comment]
I was just asking if, in a user point of view, we could hide the fact that triangles will be used during the process. The idea would be to specify two geometries:
* target : the one you want to update with z values
* source : the one with z value, which will be used to determine missing values in the "target" table

In any cases, we know that the "source" geometries will be converted into triangles, but for most of the users it can be something to complicated to understand.

**Comment by ebocher** [comment]
About the first geom (geomToDrap geometry), what about is we support only single geometry (line, point, polygon) ?

**Comment by gpetit** [comment]
* ok for the doc (I know one guy who can manage ;-) )
* my point was just "why not converting a source geometry into TIN on the fly ?". But maybe we have to discuss IRL to be more clear
* is it more complicated if we have multi-geometries ? I guess yes ... but is that insurmountable?

**Comment by ebocher** [comment]
* ok for the doc (I know one guy who can manage ;-) )
nice
* my point was just "why not converting a source geometry into TIN on the fly ?". But maybe we have to discuss IRL to be more clear
It's clear for me. I will do a proposal. The F2F will be more easy.
* is it more complicated if we have multi-geometries ? I guess yes ... but is that insurmountable?
Never but more code, more specific cases and the user is able to use SQL function to explode the geometry.

**Comment by ebocher** [comment]
Done @gpetit  ready for documentation

**Comment by gpetit** [comment]
I'm on it

**Comment by gpetit** [comment]
@ebocher you can close this issue I think
