### ISSUE TITLE
ST_SVF

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#885]
Implement a function to compute the Sky View Factor as defined in the LCZ classification.
The signature will be : 

ST_SVF(POINT, DISTANCE, RAYCOUNT, GEOMETRY)

POINT =  the point where the SVF is computed
DISTANCE = Radius of the circle considered for obstruction calculation (in meters)
RAYCOUNT = Number of rays in the circle (int)
GEOMETRY = Sky obstacle(s). The Z value of the geometry must be not null.

**Comment by ebocher** [comment]
@j3r3m1

**Comment by gpetit** [comment]
Let's go for the documentation ;-)

**Comment by ebocher** [comment]
Nice doc
http://www.h2gis.org/docs/dev/ST_SVF/
