### ISSUE TITLE
ST_ISOVIST

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#886]
Compute the visibility polygon for a given point.
See https://en.wikipedia.org/wiki/Isovist
and a nice tuto on PostGIS
https://abelvm.github.io/sql/isovists/

Signatures
```
ST_ISOVIST(point, geometry[], radius)
POINT :  the given point
geometry[] a collection of geometry
radius = distance to compute the isovist

ST_ISOVIST(point, geometry[], radius, fov)
POINT :  the given point
geometry[] a collection of geometry
radius = distance to compute the isovist
fov =field of view in degrees (eg  0 - 180 or 180 -210 ...)
```

**Comment by nicolas-f** [comment]
What is fov ? Its an array ?

**Comment by ebocher** [comment]
An Array or two distinct values

**Comment by nicolas-f** [comment]
Ok. It will be in radian like other functions. 0 value is at [x+1;0] from -pi to pi .

**Comment by ebocher** [comment]
OK

**Comment by pierromond** [comment]
Cool, I am waiting it !

**Comment by nicolas-f** [comment]
The work has been started here:

https://github.com/nicolas-f/h2gis/tree/isovist

**Comment by AbelVM** [comment]
COOL! :grin:

**Comment by ebocher** [comment]
Clap clap clap @nicolas-f  for this fast implementation

**Comment by gpetit** [comment]
Nice. The doc is in the pipe #928

**Comment by gpetit** [comment]
The doc has been produced (see #936) , and the online result : http://www.h2gis.org/docs/dev/ST_ISOVist/

**Comment by AbelVM** [comment]
:thinking: No credit/mention in the source or in the docs? Not cool

**Comment by ebocher** [comment]
This algorithm has no link with your method. 
There is already a reference  in the code source  to the algorithm we use
See  https://github.com/orbisgis/h2gis/blob/744e53b1613912389d7fa1852b6d7a9a56e87917/h2gis-utilities/src/main/java/org/h2gis/utilities/jts_utils/VisibilityAlgorithm.java#L39

What do you expect from us?

**Comment by AbelVM** [comment]
I'm good, thanks. I might have misunderstood the mention of my post as inspiration, the use of the same naming instead of the commonly used  `viewshed`, the same raytracing based approach, the same function signature and the way open source works. Sorry.

**Comment by gpetit** [comment]
Thanks @AbelVM . I read back our small exchanges (Github & Twitter) and clearly we had a misunderstood. Sorry for that.
Thanks for your blog which is very cool and keep in touch to exchange about spatial db.
