### ISSUE TITLE
ST_ShortestLine

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#907]
Implements ST_ShortestLine as PostGIS does 
http://postgis.net/docs/ST_ShortestLine.html
@gpetit

**Comment by ebocher** [comment]
@gpetit 
Doc for u

**Comment by ebocher** [comment]
pong

**Comment by ebocher** [comment]
@gpetit

**Comment by gpetit** [comment]
In the pipe ;-)

**Comment by ebocher** [comment]
Thanks
