### ISSUE TITLE
OrbisGis and H2network

### ISSUE THREAD

**Issue by pierromond** [orbisgis/h2gis#913]
The h2network functions (except ST_graph) are not found in the last snapshot of Orbisgis !

Snapshot 26/05/2018

**Comment by nicolas-f** [comment]
try

```sql
CREATE ALIAS IF NOT EXISTS H2GIS_NETWORK FOR "org.h2gis.network.functions.NetworkFunctions.load";
CALL H2GIS_NETWORK();
```

**Comment by pierromond** [comment]
Nop !

Classe "org.h2gis.network.functions.NetworkFunctions" non trouvée
Class "org.h2gis.network.functions.NetworkFunctions" not found; SQL statement:
CREATE ALIAS IF NOT EXISTS H2GIS_NETWORK FOR "org.h2gis.network.functions.NetworkFunctions.load" [90086-197]

**Comment by nicolas-f** [comment]
h2gis-network has been removed from orbisgis and it is not available in the plugins.

**Comment by nicolas-f** [comment]
The search engine is broken. Plugin is available

**Comment by nicolas-f** [comment]
![image](https://user-images.githubusercontent.com/1382241/41898238-bd08dde8-7929-11e8-9291-642a14ec8c7d.png)

**Comment by nicolas-f** [comment]
The issue is here https://github.com/orbisgis/orbisgis/issues/1261

**Comment by ebocher** [comment]
Add some informations here http://www.h2gis.org/docs/dev/h2network/ to explain H2Network .
Proposal : 

H2Network extends the H2GIS / H2 geospatial database to provide graph routing functionalities. H2Network is based on the  Java Network Analyzer library. Java Network Analyzer provides a collection of graph theory and social network analysis algorithms. These algorithms are implemented on mathematical graphs using the JGraphT library.
To install H2Network ....
