### ISSUE TITLE
H2GIS Database driver not found

### ISSUE THREAD

**Issue by bibilo** [orbisgis/h2gis#914]
Database driver not found
See in the Help for how to add drivers

Class "org.h2gis.h2spatial.internal.function.spatial.properties.ST_GeometryTypeCode" not found; SQL statement:
CREATE DOMAIN MULTIPOINT AS GEOMETRY(4) CHECK (PUBLIC.ST_GEOMETRYTYPECODE(VALUE) = 4) [90086-196] 90086/90086

How can i solve this issue?

**Comment by bibilo** [comment]
can anyone help me ? i really need to open this database

**Comment by nicolas-f** [comment]
Hi,

Try the version 1.2.3 of H2GIS:

https://github.com/orbisgis/h2gis/releases/download/v1.2.3/h2-dist-1.2.3-bin.zip

The package org.h2gis.h2spatial has been dropped since v1.3.X
