### ISSUE TITLE
Update to the last H2 1.4.199

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#919]
Since the last H2 release many changes have been introduced that break the H2GIS compatibility.

ValueGeometry.getString() returns now a EWKT representation not a WKT.
So
```java
ResultSet rs = st.executeQuery("SELECT ST_GeomFromText('POINT(0 10)', 0)");
        rs.next();
        assertEquals("POINT (0 10)", rs.getString(1))
```
will return

```java
       assertEquals("SRID=0;POINT (0 10)", rs.getString(1))
```

Note that EWKT is not a standard but a PostGIS specific format.
The PostGIS JDBC driver returns a WKT representation on rs.getString(1) 

I think H2 must be aligned on the same behaviour.

@nicolas-f @SPalominos @katzyn

**Comment by katzyn** [comment]
Unmodified version of H2 does not use EWKT for geometries with SRID=0.
```Java
ResultSet rs = s.executeQuery("SELECT 'POINT(0 10)'::GEOMETRY");
rs.next();
Geometry g = (Geometry) rs.getObject(1);
System.out.println(g);
System.out.println(rs.getString(1));
```
```SQL
POINT (0 10)
POINT (0 10)
```

`VARCHAR` is a central data type it H2 and should be able to hold anything (except for LOBs) without data loss.

If somebody uses SRID he/she should expect that extended formats will be used in binary and textual representations. If SRID is not used, H2 uses plain WKB and WKT in casts to BINARY or VARCHAR.

**Comment by katzyn** [comment]
> The PostGIS JDBC driver returns a WKT representation on rs.getString(1)

I just tested PostgreSQL 10 + PostGIS 2.4.4 + PosgreSQL JDBC 42.2.1.jre7 + PostGIS JDBC 2.2.1. Postgis extension was installed into a new database.

I inserted a `'SRID=1;POINT(1 0)'` into a table with `geometry` column.
`ResultSet.getObject(…)` returns an `org.postgis.PGgeometry` object, it means that PostGIS JDBC driver was loaded properly. `toString()` method of this object returns `SRID=1;POINT(1 0)`.

But `ResultSet.getString(…)` actually returns `010100002001000000000000000000F03F0000000000000000` just like PostgeSQL's own console. It's a hexadecimal-encoded EWKB representation.

For `'SRID=0;POINT(3 4)'` result of `ResultSet.getObject(…).toString()` is `POINT(3 4)` and result of `ResultSet.getString(…)` is `010100000000000000000008400000000000001040`. It's a WKT and a hexadecimal-encoded WKB representations.

**Comment by katzyn** [comment]
So from my point of view current development version of H2 does the right thing. It returns standard formats where it's possible and returns extended formats where standard formats cannot be used, just like PostGIS.

Mentioned `ResultSet.getString(…)` method, however, was not compatible, is not compatible, and probably will never be compatible because PostGIS uses a binary representation and H2 uses a textual representation that is more reasonable for method that returns a string.

**Comment by ebocher** [comment]
Under the pipe here https://github.com/ebocher/H2GIS/tree/prepare_H2Update
Several tests are broken.
For example assertGeometryEquals(String expectedWKT,int expectedSRID, Object valueObject)  doesn't work as expected. 
Run SpatialFunctionTest to see what happens
Note :  I'm using a local custom version of H2 where envelope, estimated_envelope have been renamed to ST_EXTENT and ST_EstimatedExtent because I'm not able to find a way to extend the two internal H2 functions.

**Comment by katzyn** [comment]
You cannot extend built-in functions and aggregates, but you can still use them in your own `ST_EstimatedExtent` function.

Functions can have `java.sql.Connection` as a first parameter, so you can call `ESTIMATED_ENVELOPE` from it, and in case of `NULL` you can call `ENVELOPE` after it (if you need it).

**Comment by ebocher** [comment]
I'm looking to create our own ST_EstimatedExtent but getEstimatedEnvelope in Function is private.
My code pattern is

```java
public class ST_EstimatedExtent extends AbstractFunction implements ScalarFunction{

    public ST_EstimatedExtent(){
        addProperty(PROP_REMARKS, "");
    }
    @Override
    public String getJavaStaticMethod() {
    return "computeEstimatedExtent";
    }
    
    public static Geometry computeEstimatedExtent(Connection connection,
                                      String tableName, String geometryColumn){
        return Function.get...
    }
}
```
Any suggestion is welcome.  ;-)

**Comment by katzyn** [comment]
I mean that you can create a `PreparedStatement` and call this function using a simple SQL command from it. This way should be reliable.

`Function` is an internal class and may be changed at any time.

**Comment by ebocher** [comment]
Seems there is an important change about the geometry access in H2 because this kind of code doesn't work

@Test
    public void test_ST_UpdateZ6() throws Exception {
        Statement st = connection.createStatement();
        ResultSet rs = st.executeQuery("SELECT ST_UPDATEZ(ST_buffer('POINT(0 0)'::GEOMETRY, 10), 120);");
        Assert.assertTrue(rs.next());
        System.out.println(((Geometry)rs.getObject(1)).getCoordinates()[0].z);
    }

It doesn't return the modified geometry the original.
Any idea ?

**Comment by katzyn** [comment]
There was a vulnerability with geometries in H2 that was recently resolved. It was possible to put untrusted geometry into H2's cache and modify it after that. As a result a key from original geometry was associated with modified geometry.

As a result poisoned cache may return this externally modified geometry instead of requested one later to any caller. It was even possible to pass fake value to another database.

It is not possible any more.

However, I don't see such weird things in your functions. They modify passed value and return it, but it should be fine in this specific situation, it's only a copy.

Also JTS has own problems with Z dimension, but H2 has a trick to pass correct number of dimensions to `WKBWriter`.

I think you should try to run this test case in debugger with breakpoints in your functions and in `ValueGeometry` to figure out what happens here.

**Comment by katzyn** [comment]
It looks like this is a Z-dimension problem, I see very similar behavior in my test functions.

**Comment by ebocher** [comment]
Yes it seems because all the tests that manipulate the z dimension have a pb

**Comment by katzyn** [comment]
Normal `POLYGON` geometry with Z dimension has `Geometry.shell.dimension == 3`.

But broken `POLYGON` geometry with Z dimension has `Geometry.shell.dimension == 2`.

**Comment by ebocher** [comment]
What do you mean by NORMAL ?

**Comment by ebocher** [comment]
In GIS field you can have both 2 and 3D. It depends on the input data model.
That why POSTGIS and H2GIS propose specific functions to update the dimension : https://postgis.net/docs/ST_Force2D.html

**Comment by katzyn** [comment]
I'm trying to build a standalone test case now.

**Comment by ebocher** [comment]
if it helps you, you can use this one to change the dimension of the geometry and create a function in H2 to test it.

```java
/**
     * Replaces the z value to each vertex of the Geometry. 
     * If the condition is equal to 1, replace all z. 
     * If the consition is equal to 2 replace only not NaN z. 
     * If the condition is equal to 3 replace only NaN z.
     *
     */
    public static class UpdateZCoordinateSequenceFilter implements CoordinateSequenceFilter {

        private boolean done = false;
        private final double z;
        private final int condition;

        public UpdateZCoordinateSequenceFilter(double z, int condition) {
            this.z = z;
            this.condition = condition;
        }

        @Override
        public boolean isGeometryChanged() {
            return true;
        }

        @Override
        public boolean isDone() {
            return done;
        }

        @Override
        public void filter(CoordinateSequence seq, int i) {
            switch (condition) {
                case 1:
                    seq.setOrdinate(i, 2, z);
                    break;
                case 2:
                    {
                        Coordinate coord = seq.getCoordinate(i);
                        double currentZ = coord.z;
                        if (!Double.isNaN(currentZ)) {
                            seq.setOrdinate(i, 2, z);
                        }       break;
                    }
                case 3:
                    {
                        Coordinate coord = seq.getCoordinate(i);
                        double currentZ = coord.z;
                        if (Double.isNaN(currentZ)) {
                            seq.setOrdinate(i, 2, z);
                        }       break;
                    }
                default:
                    done = true;
                    break;
            }
            if (i == seq.size()) {
                done = true;
            }
        }
    }
```

**Comment by katzyn** [comment]
I already have similar functions and I can create broken geometries with them is some cases.

**Comment by katzyn** [comment]
JTS 1.15.1 was used.
```Java
    public static void main(String[] args) throws Exception {
        Geometry g = new WKTReader().read("POINT (1 2)");
        System.out.println("*** We can see that geometry is 2D");
        write(g);
        System.out.println("*** < conversion to WKB and back as 2D >");
        // Comment this line:
        g = new WKBReader().read(new WKBWriter(2).write(g));
        System.out.println("*** Set the Z dimension. We can see that geometry is 3D now.");
        // Both setz1() and setz2() lead to the same result
        setz1(g);
        write(g);
        System.out.println("*** < conversion to WKB and back as 3D >");
        // Or comment this line:
        g = new WKBReader().read(new WKBWriter(3).write(g));
        System.out.println("*** Geometry is 2D again");
        write(g);

    }

    static void setz1(Geometry g) {
        g.apply(new CoordinateFilter() {
            @Override
            public void filter(Coordinate coord) {
                coord.z = 1;
            }
        });
    }

    static void setz2(Geometry g) {
        g.apply(new CoordinateSequenceFilter() {
            @Override
            public void filter(CoordinateSequence seq, int i) {
                seq.setOrdinate(i, 2, 1);
            }

            @Override
            public boolean isDone() {
                return false;
            }

            @Override
            public boolean isGeometryChanged() {
                return true;
            }
        });
    }

    static void write(Geometry g) {
        System.out.println(new WKTWriter(3).write(g));
    }
```

```
*** We can see that geometry is 2D
POINT (1 2)
*** < conversion to WKB and back as 2D >
*** Set the Z dimension. We can see that geometry is 3D now.
POINT (1 2 1)
*** < conversion to WKB and back as 3D >
*** Geometry is 2D again
POINT (1 2)
```
If any of two lines with conversions is commented the result is valid. But conversion from 2D to 2D, introduction of Z coordinate, and conversion from 3D to 3D results in unexpected 2D geometry.

I'm not sure is that a bug in JTS, or it's simply illegal to set Z value on a geometry that doesn't have an explicit Z dimension (geometries from `WKBReader` may not have it). You can see in debugger that `g.coordinates.dimension == 2` after `setz1()` (or `setz2()`), so this geometry is only a half-way 3D.

H2 actually detects them as 3D and passes 3 to `WKBWriter`, but `WKBWriter` somehow ignores it and writes it as 2D anyway, probably because `coordinates.dimension == 2`.

Feel free to use this test case as you wish.

**Comment by ebocher** [comment]
What seems problematic to me is that the tests were passing and we were already using JTS 1.15.1.
I'll investigate. Thank you for the test case.

**Comment by FObermaier** [comment]
What kind of `CoordinateSequence` are you using internally and how many dimensions does it cope with?
E.g. if you use `PackedCoordinateSequence` with a dimension of 2, setting of `CoordinateSequence.Z` will ruin the underlying sequence.

https://github.com/locationtech/jts/blob/bac855f9fe3a75af523b43f95f4b9a09b4ab5359/modules/core/src/main/java/org/locationtech/jts/geom/impl/PackedCoordinateSequence.java#L325-L342

`CoordinateArraySequence` silently updates the underlying `Coordinate`:
https://github.com/locationtech/jts/blob/bac855f9fe3a75af523b43f95f4b9a09b4ab5359/modules/core/src/main/java/org/locationtech/jts/geom/impl/CoordinateArraySequence.java#L216-L234

**Comment by FObermaier** [comment]
Using `CoordinateFilter` to update geometries is discouraged:

https://github.com/locationtech/jts/blob/jts-1.15.1/modules/core/src/main/java/org/locationtech/jts/geom/CoordinateFilter.java#L25-L28

**Comment by ebocher** [comment]
Thanks @FObermaier . I'm using CoordinateSequenceFilter see  https://github.com/ebocher/H2GIS/blob/prepare_H2Update/h2gis-functions/src/main/java/org/h2gis/functions/spatial/edit/ST_UpdateZ.java#L93

**Comment by ebocher** [comment]
@katzyn 
After some investigations it seems that the pb is not related to JTS but H2.
Some tests that modify the dimension of geometry work and others do not
This looks like a cache pb, no ?

**Comment by katzyn** [comment]
The test case above does not use H2 at all.

But the question is more complicated. Is `POINT(1, 1)` a 2D or 3D geometry? H2 stores such geometries as 2D for oblivious reasons. So you get a 2D geometry object and your function tries to set third dimension on it.

**Comment by ebocher** [comment]
Pioooouuuu
If I use

```java
st.execute("DROP TABLE IF EXISTS input_table,grid;"
                + "CREATE TABLE input_table(the_geom POINT);"
                + "INSERT INTO input_table VALUES"
                + "(ST_GeomFromText('POINT (190 300)'));");
        ResultSet rs = st.executeQuery("SELECT ST_UpdateZ(the_geom, 10) FROM input_table;");
        rs.next();
        assertGeometryEquals("POINT (190 300 10)", rs.getBytes(1));
        rs.close();
        st.execute("DROP TABLE input_table;");
```
It fails but if I cast directly the geometry 'POINT (190 300)'::GEOMETRY

It works.....


```java
st.execute("DROP TABLE IF EXISTS input_table,grid;"
                + "CREATE TABLE input_table(the_geom POINT);"
                + "INSERT INTO input_table VALUES"
                + "('POINT (190 300)'::GEOMETRY);");
        ResultSet rs = st.executeQuery("SELECT ST_UpdateZ(the_geom, 10) FROM input_table;");
        rs.next();
        assertGeometryEquals("POINT (190 300 10)", rs.getBytes(1));
        rs.close();
        st.execute("DROP TABLE input_table;");
```

**Comment by ebocher** [comment]
But the question is more complicated. Is POINT(1, 1) a 2D or 3D geometry? H2 stores such geometries as 2D for oblivious reasons. So you get a 2D geometry object and your function tries to set third dimension on it.

yes. But all H2GIS run well with H2 1.4.197 and JTS 1.5.1

**Comment by ebocher** [comment]
POINT(1, 1) is 2D
POINT(1, 1, 0) is 3D
POINT(1, 1, nan) is 3D

**Comment by katzyn** [comment]
There was a security fix in H2, there is no way back. Your test worked only due to unsafe processing of geometries in H2. Actually similar more complicated tests that store intermediate values on disk do not work even in this version.

If `POINT(1 1)` is a 2D geometry, your test case with your code is incorrect. You should convert 2D geometries to 3D form in `ST_UpdateZ`.

**Comment by katzyn** [comment]
`WKTReader` parses `'POINT(1 1)'` and `'POINT(1 1 NaN)'` into exactly the same object, there is no way to distinguish between them.
`'POINT(1 1 0)'` is different, however.

H2 persists `'POINT(1 1 0)'` as 3D and `'POINT(1 1)'` as 2D.

**Comment by katzyn** [comment]
The problem is that 2D geometries are deserialized as 2D. They may have a coordinate sequence implementation that allows you to set the third dimension, but this dimension is ignored by `WKBWriter` later.

Handling of different number of dimensions is tricky and non-intuitive in JTS.

**Comment by ebocher** [comment]
Ok seems we have a serious pb with JTS because it's not able to keep the coordinate dimension.

**Comment by katzyn** [comment]
I also found that H2 can return the same 2D geometry with 2 or 3 dimensions in coordinate system. In other aspects they are equal, no problem, but modification of Z dimension will give different results in following conversion to WKB.

H2 uses WKBReader and WKTReader as trusted sources, but they return geometries with different storage characteristics, WKTReader returns 3D-compatible geometries even for 2D.

**Comment by katzyn** [comment]
It explains why direct `'POINT (190 300)'::GEOMETRY` works, but it will work only until cache holds this 3D-compatible geometry. After its removal from the cache (or restart) you will get it in 2D-only form in your select statement. This difference can be very annoying and can lead to random unexpected failures, I have to make results from H2 fully predictable.

**Comment by ebocher** [comment]
Thanks I was checking internally what happens with 'POINT (190 300)'::GEOMETRY because it uses the same code than ST_GeomFromText.
Now I understand better and to resume we have a pb with JTS

**Comment by ebocher** [comment]
H2 guys're faster than lightning ;-)
So : 
-  release 1.5.0
- start 2.0.0-Snaphot
- go to update all the documentation.

**Comment by katzyn** [comment]
Do you need `h2.mixedGeometries` setting in H2? It was introduced specially for H2GIS.

H2 since 1.4.198 does not accept invalid geometries like `LINESTRING (1 2, 3 4 5)`. With this setting they can be accepted.

If H2GIS doesn't need this setting, I think we may remove it from H2, optional acceptance of such geometries is not a good idea.

**Comment by ebocher** [comment]
Dear @katzyn 
Feel free to remove the setting h2.mixedGeometries. We will not support invalid geometry.
Thanks

**Comment by katzyn** [comment]
Legacy `org.h2.value.ValueGeometry.get(String s, int srid)` method is now used only by some methods in `org.h2gis.unitTest.GeometryAsserts`. Could you replace invocations of this method with some alternative code?

Its current implementation in H2 simply adds a PostGIS-style SRID prefix to WKT.
```Java
    public static ValueGeometry get(String s, int srid) {
        // This method is not used in H2, but preserved for H2GIS
        return get(srid == 0 ? s : "SRID=" + srid + ';' + s);
    }
```
I guess you can use the EWKT representation in tests too.

**Comment by ebocher** [comment]
done
