### ISSUE TITLE
LGPL including GPL dependency

### ISSUE THREAD

**Issue by 44past4** [orbisgis/h2gis#920]
H2GIS is licenced under LGPL3 but https://github.com/orbisgis/h2gis/blob/master/h2gis-network/pom.xml includes a dependency to java-network-analyzer which is GPL.

**Comment by ebocher** [comment]
Thank you, it's an omission.
We will change  java-network-analyzer to LGPL asap.

**Comment by ebocher** [comment]
Fixed
