### ISSUE TITLE
Align H2 create table geometry with POSTGIS (for discussion) 

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#921]
Currently to create a geometry table in H2, the syntax is

```sql
CREATE TABLE geotable (id integer, the_geom GEOMETRY);
```

PostGIS uses

```sql
CREATE TABLE geotable (id integer, the_geom geometry(Point, 4326));
```

I think it would be good to align H2 with POSTGIS. What do you think of that?

@katzyn

**Comment by katzyn** [comment]
Plain H2 support only `GEOMETRY` data type without any modifiers. I do not use H2GIS and do not know its additional features, if H2GIS accepts `POINT` data type it's your own additions.

`geometry(Point, 4326)` in PostGIS is a geometry type that accepts only 2D `POINT` values with `SRID=4326`, such constraint ensures type, dimension system, and SRID. Do you need similar feature in H2 itself?

**Comment by ebocher** [comment]
> Plain H2 support only `GEOMETRY` data type without any modifiers. I do not use H2GIS and do not know its additional features, if H2GIS accepts `POINT` data type it's your own additions.
> 
Right, I wrote too quickly.
> `geometry(Point, 4326)` in PostGIS is a geometry type that accepts only 2D `POINT` values with `SRID=4326`, such constraint ensures type, dimension system, and SRID. Do you need similar feature in H2 itself?

From a user's point of view, I think it would be nice to harmonize syntaxes and support the same features : check type, SRID...

Any other opinions?

**Comment by gpetit** [comment]
From a user point of view, yes it could be interesting to specify in just one query the type and the srid of the geometry.
Concerning the new POINT Z(), POINT ZM () ... geometry types, how will it works ? We will have something like this ?
```sql
CREATE TABLE geotable (id integer, the_geom geometry(Point Z, 4326));
```

**Comment by katzyn** [comment]
In PostGIS you should use `pointz` without a space if data type of a column (but you can use a space in WKT representation, of course).

**Comment by gpetit** [comment]
Sounds good. Thx @katzyn

**Comment by katzyn** [comment]
The actual problem in H2 is that H2 don't have good infrastructure for data types with additional parameters above common nullability, precision, and fractional precision (scale), the only type that have something more is a `ENUM` data type which is very problematic.

I think that such feature in H2 is still possible, but I need some time to think about it and to find a way to do it properly to avoid all problems that `ENUM` data type created for us.

**Comment by ebocher** [comment]
Thanks a lot.

**Comment by ebocher** [comment]
We are ready to provide tests if needed.

**Comment by katzyn** [comment]
Also as an alternative such data type in column definition may be converted into plain `GEOMETRY` with additional `CHECK` constraint, but I'm not sure that it's a good solution, somebody may define own additional `CHECK` constraint, this is supported somehow in H2, but there were some minor problems with it and also this may complicate reading of column definition by different third-party tools.

Tests are not really needed, because they can be generated easily.

**Comment by katzyn** [comment]
PostGIS allows to use such types in `CAST` operator, it means that it is a real custom data type.

**Comment by katzyn** [comment]
Initial implementation is mostly ready, I'm currently testing it, but there is a problem with JTS. Even in version 1.16 with all its improvements in Z and M dimensions there is no way to detect number of dimensions for an empty geometry. It means that it will not be possible to insert `POINT Z EMPTY` or `GEOMETRYCOLLECTION Z EMPTY` or something similar in `GEOMETRY(POINT Z)` / `GEOMETRY(GEOMETRYCOLLECTION Z)` columns with JTS class, only with WKT string.

For JTS `Point` objects characteristics of `CoordinateSequence` are not reliable, because it may have 3 dimensions for 2D geometry. For JTS `GeometryCollection` situation is even worse, because it does not have any own properties.

**Comment by ebocher** [comment]
What do you think about reporting these issues to JTS developers?
We can point this ticket to them.

**Comment by katzyn** [comment]
You can ask them about providing a way to  distinguish `POINT EMPTY` from `POINT EMPTY Z`, `POINT EMPTY M` etc.

And also between `GEOMETRY COLLECTION EMPTY`, `GEOMETRY COLLECTION Z`, etc.

```Java
System.out.println(new WKTWriter(3).write(new WKTReader().read("GEOMETRYCOLLECTION Z (POINT Z (1 2 3))")));
System.out.println(new WKTWriter(3).write(new WKTReader().read("GEOMETRYCOLLECTION Z EMPTY")));
System.out.println(new WKTWriter(3).write(new WKTReader().read("POINT Z EMPTY")));
```
```
GEOMETRYCOLLECTION Z(POINT Z(1 2 3))
GEOMETRYCOLLECTION EMPTY
POINT EMPTY
```

**Comment by ebocher** [comment]
Wonderful..........
Is there a way to contact you in private mode ?

**Comment by katzyn** [comment]
You can see my e-mail address in git commits, feel free to send an e-mail if you wish.

**Comment by katzyn** [comment]
Actually I can remove support of `GEOMETRY(4326)` and replace in with `GEOMETRY(GEOMETRY, 4326)` to remove this deviation completely. Or it's better to support both formats? What do you think?

**Comment by ebocher** [comment]
Sorry I was out of my office.
I think it'will be bette to support only one syntax, the postgis one.

**Comment by ebocher** [comment]
> You can see my e-mail address in git commits, feel free to send an e-mail if you wish.

Cannot find it.

**Comment by katzyn** [comment]
Yes, I also found other problems with third-party software that reads such parameters incorrectly. Let's use `GEOMETRY(GEOMETRY, 4326)` format too.

katzyn AT gmail DOT com

**Comment by katzyn** [comment]
However, I don't like that SRID 0 means any SRID in PostGIS, it's not very intuitive and it provides no way to ensure default SRID 0 on geometries. So I think this difference is reasonable. You can use `GEOMETRY(POINT)` format in both databases to allow any SRID.

**Comment by ebocher** [comment]
Sorry I don't understand "I don't like that SRID 0 means any SRID in PostGIS".

**Comment by ebocher** [comment]
In your last PR you talk about "Some third-party tools" . 
Do you have any feedback on that? Who are they? Who are they?

**Comment by katzyn** [comment]
The biggest problem now is a lack of dimension system information in JTS.

```Java
Connection c = DriverManager.getConnection("jdbc:h2:mem:1");
Statement s = c.createStatement();
s.execute("CREATE TABLE TEST(G GEOMETRY(GEOMETRYCOLLECTION))");
s.execute("CREATE TABLE TESTZ(G GEOMETRY(GEOMETRYCOLLECTION Z))");
PreparedStatement ps = c.prepareStatement("INSERT INTO TEST VALUES (?)");
PreparedStatement psZ = c.prepareStatement("INSERT INTO TESTZ VALUES (?)");
ps.setString(1, "GEOMETRYCOLLECTION EMPTY");
ps.executeUpdate();
ps.setObject(1, new WKTReader().read("GEOMETRYCOLLECTION EMPTY"));
ps.executeUpdate();
psZ.setString(1, "GEOMETRYCOLLECTION Z EMPTY");
psZ.executeUpdate();
psZ.setObject(1, new WKTReader().read("GEOMETRYCOLLECTION Z (POINT Z(1 2 3))"));
psZ.executeUpdate();
// Next insert fails with SQLIntegrityConstraintViolationException
psZ.setObject(1, new WKTReader().read("GEOMETRYCOLLECTION Z EMPTY"));
psZ.executeUpdate();
```

If you want to insert empty geometry with column with Z, M, or ZM dimension system in constraint you're in trouble. A proper fix for it needs some improvement on JTS side. Both `GeometryCollection` instances here are exactly the same and cannot be distinguished by H2. So H2 assumes them as 2D.

**Comment by katzyn** [comment]
They both use the same singleton instance of `CoordinateArraySequenceFactory` and don't have any points with coordinates.

`GeometryCollection` that was returned by `WKTReder` from `GEOMETRYCOLLECTION Z (POINT Z(1 2 3))` has a point with X, Y, and Z coordinates that allows H2 to detect the whole collection as a collection in Z dimension system.

When H2 parses (E)WKT by itself it preserves the dimension system from `Z`, `M`, or `ZM` flag.

**Comment by ebocher** [comment]
What do you think about initializing an empty GeometryCollection with only one coordinate with the right dimensions (X, Y[Z M] ?

**Comment by katzyn** [comment]
`GeometryCollection` don't have any points, coordinates, or coordinate sequences at all.

I think that JTS should have some dimension system parameter in its base `Geometry` class.

**Comment by katzyn** [comment]
Factories also don't have dimension system information.

`CoordinateSequence` instances in `Point`, `LineString` and similar geometries have, but it's not reliable too. Try this in JTS 1.16.0-RC1:
```
Point p = (Point) new WKTReader().read("POINT (1 1)");
System.out.println(p.getCoordinateSequence().getDimension());
System.out.println(p.getCoordinateSequence().getMeasures());
```
It prints 3 and 0. This is a Z dimension system. But this point is obliviously 2D. H2 accepts such point as 2D, because its coordinates are x=1, y=1, z=NaN.

**Comment by ebocher** [comment]
Done with H2GIS 2.0
thanks to @katzyn
