### ISSUE TITLE
ST_OrientedEnvelope

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#922]
It will be great to have the same function : 

* http://www.bostongis.com/blog/index.php?/archives/270-Coming-PostGIS-2.5-ST_OrientedEnvelope.html
* https://postgis.net/docs/manual-dev/ST_OrientedEnvelope.html

We already have http://www.h2gis.org/docs/dev/ST_MinimumRectangle/. So maybe, just adding an alias ?

@ebocher @nicolas-f

**Comment by ebocher** [comment]
Done

**Comment by gpetit** [comment]
Thx !

**Comment by ebocher** [comment]
Don't forget to update the doc
