### ISSUE TITLE
Update OSMRead

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#923]
Update the OSMRead functions To follow exactly the OSM XML model.
Remove the tags table and store key, value in each node, way and relation tag tables.
Add a general table to store osm file metadata (timestamp, generator...)

**Comment by ebocher** [comment]
Do you want this change in the current version or the last major version (2.0 ) ?
@gpetit , @nicolas-f

**Comment by gpetit** [comment]
2.0 ?

**Comment by nicolas-f** [comment]
It breaks compatibility with existing script, so yes 2.0

**Comment by ebocher** [comment]
Done https://github.com/orbisgis/h2gis/pull/975
The H2GIS doc for the V2.0 must updated.
@gpetit
