### ISSUE TITLE
1.4.0 maven release?

### ISSUE THREAD

**Issue by moovida** [orbisgis/h2gis#942]
Hi, I see that the latest version is the 1.4.0, but I can't find it on maven.

Would it be possible to release it there as with the other versions?

Thanks you

**Comment by moovida** [comment]
Oh, I apologize, I only now noticed that the only 1.4.0 artifact missing is the h2gis-ext.
The others are available.

**Comment by moovida** [comment]
I can't find on the documentation how to do the:
```
H2GISExtension.load(connection);
```
The example is still on 1.3.2 I guess: https://github.com/orbisgis/orbisgis-samples/blob/master/demoh2gis/src/main/java/org/orbisgis/demoh2gis/Main.java

**Comment by ebocher** [comment]
Hi Andrea,

H2GISExtension.load(connection) has been removed in 1.4.0 and replaced by H2GISFunctions
see here https://github.com/orbisgis/h2gis/blob/6d7f181f68bc2aa58642f9a443edc51605b8d3fc/h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java#L479
and a SQL example at http://www.h2gis.org/docs/1.4.0/quickstart/
Hope this help
