### ISSUE TITLE
Strange issue with ST_XMin and collect

### ISSUE THREAD

**Issue by moovida** [orbisgis/h2gis#945]
I am trying to get table boundaries (in this case polygon layer of naturalearth) with:

```
SELECT ST_XMin(ST_collect(THE_GEOM)) FROM countries
```
but I am getting:

```
An error occurred: General error: "java.lang.IllegalArgumentException: Invalid ordinate index: 2"; SQL statement:
SELECT ST_XMin(ST_collect(THE_GEOM)) FROM countries
 [50000-197]
```

The same happens with ST_Accum. I am at foss4gasia and might be a bit dazed and confused, so I rather ask :-)

Is this a bug or am I doing something wrong?

**Comment by ebocher** [comment]
Which version of H2GIS are you using?

The following request works in the master

```sql
SELECT ST_XMIN(ST_COLLECT(the_geom)) FROM (select ST_MakePoint(A.X , B.X) the_geom FROM SYSTEM_RANGE(12,50) A,SYSTEM_RANGE(30,50) B)
```
Can you share your data ?

**Comment by ebocher** [comment]
@moovida  any news ?

**Comment by moovida** [comment]
Hi @ebocher , sorry for the delay. This has to be something with the way I create my data I guess, but I can't see the problem. 

Find attached a test db that should reproduce the problem. I am using the master of 2-3 weeks ago.

In there for me 
```
SELECT ST_XMin(ST_collect(THE_GEOM)) FROM gpslogs
```
produces the said error.


[h2gis_test.mv.db.zip](https://github.com/orbisgis/h2gis/files/2662804/h2gis_test.mv.db.zip)

**Comment by moovida** [comment]
This is quite odd. I have no idea how this is possible...

Now that 1.5.0 is out, I will clean up everything and try from scratch. I will close this here and in case reopen it again if I find a way to reproduce this.

**Comment by moovida** [comment]
Even if 1.5.0 is not out, I have to reopen this to ask for help.
I am now having this issue with any ST_collect query. 

I debugged this down into the bottom and see that it is happening in H2 itself, exactly inside: org.h2.value.ValueGeometry.getDimensionCount(Geometry)

In there it breaks and I have no idea why, since it is taking a Geometry and this should be solid.

It breaks when it tests:

```
            if (!Double.isNaN(coordinateSequence.getOrdinate(i, 2))) {
                foundZ = true;
            }
```
where it rightfully breaks in this (org.locationtech.jts.geom.CoordinateXY):

```
  public double getOrdinate(int ordinateIndex) {
      switch (ordinateIndex) {
      case X: return x;
      case Y: return y;
      }
      throw new IllegalArgumentException("Invalid ordinate index: " + ordinateIndex);
  }
```

But passing 2 will never work and since it is hardcoded, I have no idea how this should even work. 

Am I pulling some wrong dependency of H2? 
Any other clue that could help me?

**Comment by ebocher** [comment]
Are you using JTS 1.16 because CoordinateXY has been introduced since 1.15 and H2GIS supports only 1.15.

**Comment by moovida** [comment]
Oh man, you made my day. I didn't figure this could be a jts thing. And yes, I was on jts 1.16.
Thanks and sorry for the noise.

**Comment by ebocher** [comment]
> Oh man, you made my day. I didn't figure this could be a jts thing. And yes, I was on jts 1.16.
> Thanks and sorry for the noise.

You are welcome

**Comment by ebocher** [comment]
> On a sidenote, there is a very sad ramification to this. At the current time it is not possible to use H2GIS in its latest version with any version of geotools.
> 
> This is due to the fact that geotools moved from jts 1.14 directly to 1.16. So with the old the jts namespace is wrong and with the new, the problem described in this issue occurrs.
> 
> So for these two projects to work together right now, I would have to go back to geotools 19.4 and use H2GIS 1.4.0
> This is so sad...

The last H2 database will fix some issues on geometry dimensions.
https://github.com/orbisgis/h2gis/issues/919
We hope that this will improve the geometric management in H2 and H2GIS
