### ISSUE TITLE
Use on Android?

### ISSUE THREAD

**Issue by OnkelTem** [orbisgis/h2gis#948]
Hi folks

I couldn't find any mentions of Android platform neither on H2Gis website nor here. I know it's a little bit silly way to acquire compatibility matrix so I ask: can I use it in an Android app? I need to store and query polygons in the app. Apart from this library and Spatialite (which was last updated back in 2012) I haven't found anything :-/

**Comment by ebocher** [comment]
H2GIS should be able to work with Android.
Feel free to test it and give us a feedback.
Thanks

**Comment by OnkelTem** [comment]
Yeah, thank you very much for the support :) I'll try!
