### ISSUE TITLE
H2GIS jar in maven central repository still has vividsolution dependency

### ISSUE THREAD

**Issue by sumitnair** [orbisgis/h2gis#955]
http://central.maven.org/maven2/org/orbisgis/h2gis/1.4.0/h2gis-1.4.0.pom

<dependency>
            <groupId>org.orbisgis</groupId>
            <artifactId>h2gis</artifactId>
            <version>1.4.0</version>
  </dependency>
correct artifact needs to be uploaded to repository

**Comment by SPalominos** [comment]
H2GIS 1.4.0 use the version 1.14 of JTS core and IO which are under `com.vividsolution`. In H2GIS 1.5.0 (SNAPSHOT) we will use JTS 1.15 which is under `org.locationtech.jts`.

**Comment by sumitnair** [comment]
Can i get H2GIS 1.5.0 (SNAPSHOT)  maven central repository

**Comment by SPalominos** [comment]
Not from maven central, but you can get it from our own nexus. Just add to you pom.xml the `h2gis` dependency and  OrbisGIS `osgi-maven-snapshot` repository:
````xml
...
    <dependencies>
    ...
        <dependency>
            <groupId>org.orbisgis</groupId>
            <artifactId>h2gis</artifactId>
            <version>1.5.0-SNAPSHOT</version>
        </dependency>
    ...
    </dependencies>
...
    <repositories>
    ...
        <repository>
            <id>orbisgis-nexus-snapshot</id>
            <name>OrbisGIS nexus snapshot repository</name>
            <url>http://nexus.orbisgis.org/content/repositories/osgi-maven-snapshot</url>
        </repository>
    ...
    </repositories>

**Comment by sumitnair** [comment]
@SPalominos could you also provide SNAPSHOT version for `h2gis-functions` and `h2spatial` which uses `org.locationtech`

**Comment by ebocher** [comment]
As @SPalominos  you are able to use http://nexus.orbisgis.org/content/repositories/osgi-maven-snapshot where you will find all h2gis deps

**Comment by sumitnair** [comment]
@ebocher Thanks. But i cant see `h2spatial` , is there a separate repository for it ? 

I am using the below dependency which still uses 'com.vividsolutions'
`<groupId>org.orbisgis</groupId>
   <artifactId>h2spatial</artifactId>
   <version>1.2.4</version>`

http://nexus.orbisgis.org/content/repositories/osgi-maven-snapshot/org/orbisgis/h2spatial/

**Comment by sumitnair** [comment]
Thanks @SPalominos  @ebocher
