### ISSUE TITLE
ST_FORCE2D and H2GIS2.0

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/h2gis#983]
I use the following command in a code using H2GIS 2.0
```groovy
SELECT ST_force2D('MULTILINESTRING((268394.46568222373 6745339.923834022, 268396.99851297046 6745339.229782337))::GEOMETRY');
```
It works using Orbisgis (with H2GIS 1.5) but it does not work neither with IntelliJ nor the groovyConsole when using H2GIS 2.0.
The returned error is:
> org.h2.jdbc.JdbcSQLDataException: Erreur lors de la conversion de données "MULTILINESTRING((268394.46568222373 6745339.923834022, 268396.99851297046 6745339.229782337))::GEOMETRY"
Data conversion error converting "MULTILINESTRING((268394.46568222373 6745339.923834022, 268396.99851297046 6745339.229782337))::GEOMETRY"; SQL statement:
SELECT ST_force2D('MULTILINESTRING((268394.46568222373 6745339.923834022, 268396.99851297046 6745339.229782337))::GEOMETRY'); [22018-199]

**Comment by nicolas-f** [comment]
Misplaced quote:
```sql
SELECT ST_force2D('MULTILINESTRING((268394.46568222373 6745339.923834022, 268396.99851297046 6745339.229782337))'::GEOMETRY);
```

**Comment by j3r3m1** [comment]
right then the error message is:

> org.h2.jdbc.JdbcSQLNonTransientException: Exception lors de l'appel de la fonction définie par l'utilisateur: "force2D(MULTILINESTRING ((268394.46568222373 6745339.923834022, 268396.99851297046 6745339.229782337))): Points of LinearRing do not form a closed linestring"
Exception calling user-defined function: "force2D(MULTILINESTRING ((268394.46568222373 6745339.923834022, 268396.99851297046 6745339.229782337))): Points of LinearRing do not form a closed linestring"; SQL statement:
SELECT ST_force2D('MULTILINESTRING((268394.46568222373 6745339.923834022, 268396.99851297046 6745339.229782337))'::GEOMETRY); [90105-199]

**Comment by nicolas-f** [comment]
Without full stack trace its hard to guess but I think the issue is here:

https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/spatial/convert/GeometryCoordinateDimension.java#L133
