### ISSUE TITLE
Trouble with st_makepolygon

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/h2gis#994]
Is it possible to create a polygon extruded from several holes ? I have tried the following query but I got error since the function only accepts linestring
`SELECT ST_MAKEPOLYGON('LINESTRING((0 0, 4 0, 4 4, 0 4, 0 0))', 'MULTILINESTRING((0.5 0.5, 1 0.5, 1 2, 0.5 2, 0.5 0.5), (1.5 0.5, 2.5 0.5, 2.5 2, 1.5 2, 1.5 0.5))');`

**Comment by ebocher** [comment]
Seems there is a pb. I will check

**Comment by ebocher** [comment]
Ok seems a pb in the first input geometry LINESTRING((0 0, 4 0, 4 4, 0 4, 0 0)) is not a valid WKT representation. It works with LINESTRING(0 0, 4 0, 4 4, 0 4, 0 0)
